UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Ikigai is a reason to get up</h2>
<ul><li>More than a job title, ikigai is the intersection of meaning, usefulness, joy, and sustainable engagement that pulls you into life each morning.</li></ul>
<h2>2. Longevity cultures stay purposeful</h2>
<ul><li>Okinawan examples emphasize community, moderate eating, daily movement, and continuing contribution rather than abrupt emptiness after work ends.</li></ul>
<h2>3. Never retire from meaning</h2>
<ul><li>Stopping paid work need not mean stopping contribution; keep roles, hobbies, and service that give shape to your days.</li></ul>
<h2>4. Flow reveals what fits you</h2>
<ul><li>Activities where challenge and skill meet, time softens, and attention absorbs you are clues to your living ikigai.</li></ul>
<h2>5. Small daily habits compound</h2>
<ul><li>Hara hachi bu, walking, friendship circles, and presence reduce stress and support a long, enjoyable life.</li></ul>
<h2>6. Follow rules of a lighter life</h2>
<ul><li>Stay curious, smile, reconnect with nature, live in the moment, and keep following what makes you feel alive.</li></ul>

<h1>PART 2 — IKIGAI</h1>
<h2>A 25-Minute Read Summary</h2>

<h3>Chapter 1: A Reason for Being</h3>
<p>Héctor García and Francesc Miralles popularized a simple Japanese idea for a global audience: ikigai, often translated as a reason for being—or a reason to get up in the morning. It is not a single thunderbolt of destiny. It is the felt sense that your days are worth inhabiting because something in them matters to you and connects you to others. That something might be craft, caregiving, learning, gardening, teaching, repairing, creating, or serving a community. Ikigai can be quiet. It does not require fame. It requires enough meaning that life feels directed rather than merely endured.</p>
<p>Western career advice sometimes collapses purpose into a Venn diagram of what you love, what you are good at, what the world needs, and what you can be paid for. The authors explore related themes, but the heart of the book is broader than salary optimization. Ikigai can exist in unpaid roles and humble routines. A person may find it in preparing breakfast for family, practicing a martial art, mentoring neighbors, or tending plants. The question is less “What is my brand?” and more “What makes ordinary mornings feel alive?”</p>
<p>Start by noticing what you already do without being forced—activities you return to, talk about, or miss when absent. Notice also what drains you even when it looks impressive on paper. Ikigai is discovered through attention to lived energy, not only through abstract brainstorming. Keep a one-week log of moments when you felt useful, absorbed, or quietly glad. Patterns in that log are early maps.</p>
<p>It helps to separate ikigai from hustle slogans. A reason for being is not a command to monetize every passion or to treat rest as moral failure. In Japanese usage discussed by the authors, ikigai can be humble and local. The pressure to turn purpose into a personal brand can actually distance you from it. If your current season only supports a small flame—reading to a child, practicing scales, helping a parent—that flame still counts. Protect it from contempt. Big purpose often grows from guarded small purpose.</p>
<p>Another clarification: ikigai is not found only by thinking harder. Rumination can mimic depth while avoiding contact with life. Alternate reflection with contact: make, serve, walk, talk, try. Then reflect on what the contact revealed. This loop—act, notice, adjust—is the real search method. People who only journal about purpose sometimes stall; people who only grind without reflection sometimes miss the signal. Use both.</p>
<p><strong>Lesson:</strong> Ikigai is a practical reason to rise—meaning found in real activities, not only in grand career declarations.</p>

<h3>Chapter 2: Lessons from Longevity Villages</h3>
<p>The book draws heavily on observations from places associated with long, healthy lives, especially communities in Okinawa. The authors describe elders who remain socially woven into daily life, eat with moderation, move naturally through walking and chores, and keep a sense of purpose into late age. Longevity here is not presented as a miracle supplement stack. It looks like a culture: shared meals, familiar faces, low-grade daily activity, and a reason to keep showing up.</p>
<p>One striking theme is belonging. People with strong social ties—sometimes organized as mutual-support circles—have others who notice when they are missing, celebrate small events, and share burdens. Isolation, by contrast, is treated as a quiet risk factor for both body and spirit. Another theme is pace. Life is not framed as a race to maximize output until collapse. There is room for conversation, ritual, and unhurried competence at tasks that keep a household and community running.</p>
<p>You do not need to relocate to adopt the pattern. Strengthen local ties. Walk more of your errands. Share food. Keep intergenerational contact if you can. Design a week that includes contribution and companionship, not only consumption and screens. The longevity lesson is holistic: purpose, relationships, movement, and diet work together more than any single hack.</p>
<p>Longevity villages also illustrate the power of identity beyond youth. Elders remain visible contributors, not hidden problems. That cultural framing changes how aging feels in the body. If your surrounding culture treats aging as pure decline, borrow a counter-image: competence, humor, mentoring, and seasonal rituals that include older people as central. Even one intergenerational friendship can recalibrate what you expect from later life—and what you invest in now to arrive there capable.</p>
<p>Import habits carefully without romanticizing. Not every traditional practice transfers cleanly, and not every long-lived person follows a perfect checklist. Look for principles: belonging, moderation, movement, purpose, outdoor time, and low chronic drama. Then translate principles into your city, budget, and personality. Translation is the work. Imitation without fit becomes a costume.</p>
<p>When you visit or read about long-lived communities, look past novelty foods and toward social architecture: who eats together, who is needed, who walks, who laughs. Copy architecture before you copy recipes.</p>
<p><strong>Lesson:</strong> Long, vibrant lives are supported by purpose, community, gentle daily movement, and moderate living—not by one isolated trick.</p>

<h3>Chapter 3: Finding Your Ikigai</h3>
<p>Finding ikigai is less like decoding a secret and more like following breadcrumbs. Ask what you loved doing before status concerns took over. Ask what people thank you for without prompting. Ask what problems you notice that others overlook. Ask what you would do if money were handled for a season—not as fantasy escape, but as a clue to intrinsic pull. Then test small. Purpose rarely arrives fully funded and scheduled. It arrives as experiments that either energize or empty you.</p>
<p>Many people wait for perfect clarity before acting. The authors’ spirit suggests the reverse: act in small, reversible ways and let clarity grow. Volunteer once. Take a beginner class. Build a tiny habit around a craft. Offer a skill to a neighbor. Ikigai becomes clearer in motion because motion generates feedback. You learn what feels forced and what feels like home.</p>
<p>Also accept that ikigai can evolve. The reason that animated you at twenty-five may shift at fifty. Seasons of caregiving, recovery, or reinvention change the shape of meaning. That is not failure. Treat ikigai as a living practice you recalibrate, not a permanent tattoo. Revisit your log each season and update what deserves more hours.</p>
<p>A practical discovery workshop looks like this: list ten activities from the past year that produced pride, usefulness, or absorption. Circle the three you would gladly repeat weekly even without applause. For each circled item, write the smallest weekly version—thirty minutes, one session, one message of outreach. Put those versions on a calendar for four weeks. At the end, rate energy and meaning from one to ten. Keep what scores high. Replace what scores low. This is empirical ikigai, not mystical waiting.</p>
<p>Include constraints honestly. Health, money, caregiving, and location shape the field of play. Ikigai within constraints is still ikigai. In fact, constraints often sharpen creativity. The question “What is meaningful within my real life?” beats “What would I do if I were someone else?” Self-acceptance is part of the map.</p>
<p><strong>Lesson:</strong> Discover ikigai through experiments and attention to energy, accepting that your reason for being can evolve across life seasons.</p>

<h3>Chapter 4: Never Retire Completely</h3>
<p>A major warning in the book concerns abrupt retirement from all meaningful roles. When work has been someone’s primary structure, stopping overnight can remove community, competence, and contribution in one cut. The authors highlight elders who keep gardening, teaching informally, crafting, or helping family—forms of engagement that preserve identity and momentum. The point is not that everyone must earn forever. It is that humans thrive with purposeful activity.</p>
<p>Modern culture often treats retirement as pure leisure. Leisure matters, but endless unstructured time can drift into emptiness for people who need a why. Plan a second act before you need it. What will you practice, make, teach, or join? Who will you see weekly? What modest goals will give shape to Tuesday mornings? Even part-time mentoring or community projects can protect the sense of being needed.</p>
<p>If you are far from retirement, the lesson still applies. Do not outsource your entire identity to a job title. Build skills and relationships that can travel with you if roles change. Keep a craft alive. Stay useful in ways that are not dependent on one employer. Ikigai that survives career shocks is ikigai rooted in who you are, not only where you clock in.</p>
<p>Organizations can apply this lesson by designing off-ramps that preserve contribution: mentoring roles, alumni communities, part-time project work, and knowledge transfer that honors identity. Individuals can build a “portfolio of meaning” early: one craft, one service role, one friendship circle, one body practice. When a job ends, the portfolio remains. This is career resilience with a human face.</p>
<p>If you recently retired or were laid off and feel flat, do not panic-diagnose yourself as purposeless. Flatness is often withdrawal from structure. Rebuild structure in kind increments: morning walk, weekly class, scheduled call, volunteer shift. Purpose returns more easily to a rhythmic life than to an empty open prairie of time. Start rhythmic, then refine meaningful.</p>
<p><strong>Lesson:</strong> Stay active with purpose across life stages; ending a job should not mean abandoning contribution and structure.</p>

<h3>Chapter 5: Flow and Meaningful Engagement</h3>
<p>The authors connect ikigai to flow—the state of deep absorption popularized by Mihaly Csikszentmihalyi, where challenge and skill are well matched, distraction fades, and time feels different. Flow is not constant bliss. It is engaged attention. When you regularly find flow in an activity, that activity is a strong candidate for your ikigai, or at least a pillar of it. Conversely, chronic boredom or chronic overwhelm suggests a mismatch worth adjusting.</p>
<p>To cultivate flow, reduce friction around meaningful work. Prepare tools in advance. Set clear near-term aims. Silence unnecessary notifications. Choose tasks slightly beyond your comfort zone so attention has something to grip. If work is too easy, add complexity. If it is too hard, break it into learnable chunks. Flow loves clarity and immediate feedback.</p>
<p>Track your personal flow triggers: music or silence, morning or evening, solo or collaborative, hands-on or analytical. Then protect those conditions the way you would protect a vital appointment. A life with regular flow moments tends to feel richer even when external circumstances are imperfect, because you are frequently inside something that uses you well.</p>
<p>Flow is easier when goals are clear and feedback is near. If your work is bureaucratic and vague, create personal clarity: define a daily artifact, a checklist, or a craft standard you control. If your ikigai lives outside work, protect uninterrupted blocks like appointments with someone you respect—because they are. Phone fragmentation destroys flow more often than lack of passion does. Passion cannot compete with a buzzing pocket unless you design the contest.</p>
<p>Also notice collaborative flow. Some people light up in ensembles—bands, kitchens, code pairs, community organizing. Others need solitude. Honor your channel. Forcing solitary flow on a highly social person, or constant collaboration on a solitary person, creates false negatives about “having no purpose.” Match environment to temperament as part of the search.</p>
<p><strong>Lesson:</strong> Seek challenge-skill balance and deep absorption; flow experiences are practical clues to what fuels your ikigai.</p>

<h3>Chapter 6: Hara Hachi Bu and Eating Lightly</h3>
<p>Among the longevity habits associated with Okinawa is hara hachi bu—the practice of stopping eating when you are about eighty percent full. The idea is modest: leave a little room rather than eating to strain. This is not framed as a punitive diet. It is a cultural cue toward moderation, slower meals, and attentiveness to bodily signals. Overeating regularly taxes the body; mindful sufficiency supports comfort and long-term health.</p>
<p>Practically, this can mean smaller default portions, pausing mid-meal, eating without constant screens, and favoring foods that nourish without requiring heroic restriction narratives. Plant-forward, colorful plates and shared meals appear often in longevity discussions the authors explore. The social context matters: eating with others can slow you down and turn nutrition into belonging.</p>
<p>You do not need perfection. Aim for a sustainable tilt. Notice the difference between hunger, habit, and emotional eating. Stop at satisfied more often than stuffed. Pair eating changes with walking and sleep rather than treating food as the only lever. Ikigai includes caring for the body that carries your purpose.</p>
<p>Eating lightly also pairs with gratitude and sensory attention. When meals are rushed fuel, it is easy to overrun fullness cues. When meals include tasting, pausing, and thanks, sufficiency arrives sooner. This is one reason shared, unhurried meals appear in longevity sketches. You can approximate them even alone: put food on a plate, sit, chew, stop. If a medical condition requires a specific diet, follow clinical guidance and use hara hachi bu only as a compatible mindfulness layer, not as dogma.</p>
<p>Beware using longevity nutrition as a new perfection prison. Ikigai includes ease. Aim for “often enough,” not flawless purity. A life of joyful meals with occasional excess may support well-being better than a life of lonely restriction. Moderation includes moderating your self-critique.</p>
<p><strong>Lesson:</strong> Practice stopping around comfortably satisfied—hara hachi bu—as a moderate, sustainable eating habit linked to longevity cultures.</p>

<h3>Chapter 7: Movement, Nature, and Daily Motion</h3>
<p>In the communities the book celebrates, movement is often built into life rather than quarantined in punishing gym sessions. Walking to see friends, tending gardens, standing, stretching, and light daily activity keep bodies capable. Intense exercise can be wonderful, but the longevity pattern emphasizes consistency and enjoyment. A body that moves a little every day often fares better than a body that swings between total stillness and rare exhaustion.</p>
<p>Nature appears as a restorative partner. Time outside can lower mental noise and reconnect you to seasons larger than your inbox. Even short outdoor walks between tasks can reset attention. If you live in a dense city, seek parks, waterfronts, morning light, or plants you care for at home. Movement plus nature is a simple compound for mood and health.</p>
<p>Design your environment to invite motion: stairs when reasonable, walking meetings, a standing break each hour, a hobby that uses your hands and legs. The goal is not athletic glory. The goal is remaining able—able to play with children, travel, work in a garden, or walk to a friend’s house—so your ikigai remains physically expressible.</p>
<p>If gyms intimidate or bore you, choose play: dancing, cycling for errands, hiking clubs, gardening, swimming, stretching while listening to music. Enjoyment predicts adherence, and adherence predicts benefit. Track how you feel after movement for two weeks—mood, sleep, pain—rather than only weight or pace. Let feeling become feedback. The authors’ broader message is that a movable body supports a movable mind, and both support a reason to get up.</p>
<p>Make movement social when possible. A standing walking date doubles as community care. A family evening stroll reduces screen time without a lecture. These bundles are efficient ikigai design: one habit serving health, relationship, and presence together.</p>
<p><strong>Lesson:</strong> Favor enjoyable daily movement and time outdoors so your body stays able to carry a meaningful life.</p>

<h3>Chapter 8: Community and Mutual Support</h3>
<p>Ikigai is personal, but it is rarely solitary. The authors emphasize friendship, family ties, and mutual-support groups as protective structures. Knowing you are expected somewhere matters. Having people who would notice your absence matters. Sharing celebrations and hardships keeps stress from becoming a private prison. In a culture of extreme individualism, this can sound soft. In longevity research conversations, it looks essential.</p>
<p>Build community on purpose. Join a class that meets weekly. Host a simple recurring meal. Check on a neighbor. Reinvest in a friend you have neglected. Quality matters more than a huge network. A few reliable ties outperform dozens of shallow contacts. If you are introverted, choose lower-stimulation formats: walks, small groups, shared projects with clear roles.</p>
<p>Community also sharpens ikigai because other people reflect your strengths back to you. They ask for your help in specific ways. They invite you into roles you might not claim alone. Service becomes a mirror. When you feel stuck about purpose, ask who already relies on you in small ways—and whether you want to deepen that usefulness.</p>
<p>For people who fear burdening others, remember that mutual support is mutual. Receiving help is part of community competence. So is offering help without keeping score in a petty way. If you have no circle now, build one through repeated proximity: same class, same volunteer shift, same bench at the same park. Friendship often follows familiarity more than chemistry alone. Consistency is an underrated social skill.</p>
<p>Digital community can help but rarely replaces embodied presence entirely. Prefer formats with real names, recurring meetings, and shared effort. A Discord server can support a craft; a weekly in-person meal often anchors a life. Use both if you need, and notice which one leaves you more settled afterward.</p>
<p><strong>Lesson:</strong> Strong, mutual relationships protect health and reveal purpose; invest in a few ties where you are genuinely expected.</p>

<h3>Chapter 9: Resilience and a Lighter Stress Load</h3>
<p>A long life is not a life without difficulty. The difference is often how stress is metabolized. The book points toward attitudes and habits that keep stress from becoming chronic identity: staying busy with meaningful tasks, maintaining perspective, laughing, sleeping, and refusing to dramatize every setback into a final verdict. Resilience here looks practical—return to routine, lean on friends, keep hands occupied with useful work.</p>
<p>Modern stress is frequently cognitive: endless alerts, comparison, and ambiguity. Counter it with boundaries. Create phone-free pockets. Finish one thing before opening five new loops. Practice saying no to obligations that are pure status theater. Stress reduction is not laziness; it is protecting the attention your ikigai needs.</p>
<p>When hardship arrives—illness, loss, job change—ikigai can shrink to a smaller radius without disappearing. Maybe your reason for today is making soup, calling one person, or sitting in the sun. That still counts. A flexible sense of purpose survives winters better than a brittle, all-or-nothing dream.</p>
<p>Stress tools that fit the ikigai ethos are simple: sleep windows, nature breaks, breathing during transitions, and meaningful busyness rather than frantic busyness. There is a difference between being occupied with what matters and being scattered across what does not. Audit your obligations quarterly. Remove one drain. Add one restorative practice. Resilience is often subtraction plus rhythm, not endless coping hacks piled on an overcrowded life.</p>
<p>Mindset matters too. The authors highlight cheerful engagement and a certain lightness—smiling, giving thanks, not dramatizing every inconvenience. This is not toxic positivity. It is proportion. Save deep grief for real losses. Refuse to spend premium attention on trivial irritations. That allocation protects energy for your actual reasons for being.</p>
<p><strong>Lesson:</strong> Lower chronic stress with boundaries and supportive routines, and let purpose flex smaller during hard seasons without vanishing.</p>

<h3>Chapter 10: The Ten Rules Spirit</h3>
<p>Near the end, the authors gather guiding rules associated with ikigai—practical maxims rather than rigid commandments. Themes include staying active, taking it slow, not filling life with only what you are told you should want, being surrounded by good people, reconnecting with nature around you, giving thanks, living in the moment, and following your ikigai. The list varies in popular summaries, but the spirit is consistent: choose a vivid, grateful, present, socially rooted life.</p>
<p>These rules work best as daily cues, not posters you ignore. “Live in the moment” becomes one breath before a meal. “Smile” becomes a deliberate softening when you greet someone. “Follow your ikigai” becomes a calendar block for the activity that makes you feel alive. Tiny implementations beat grand declarations that change nothing by Wednesday.</p>
<p>Pick three rules that address your current imbalance. If you rush, practice slow. If you isolate, practice people. If you postpone joy for a future that never arrives, practice a small present pleasure tied to meaning. Review them weekly. Ikigai is a compass; rules are sticky notes on the compass glass.</p>
<p>Turn rules into if-then designs. If it is morning, then step outside for light. If you eat, then pause at seventy-to-eighty percent fullness. If you feel lonely, then message one person from your circle. If you have a free hour, then touch your ikigai activity before scrolling. If-then plans reduce decision fatigue and make philosophy behavioral. Post your three if-then lines where you will see them. Review on Sundays. Adjust seasonally. Rules that evolve stay alive; rules that freeze become wallpaper.</p>
<p>Share a rule with a friend for light accountability—not surveillance. “I’m practicing living in the moment at dinner; ask me how it went.” Social reinforcement is on-brand for a philosophy that refuses isolated self-optimization.</p>
<p><strong>Lesson:</strong> Use ikigai’s simple rules—presence, gratitude, good company, nature, and following what enlivens you—as daily cues, not slogans.</p>

<h3>Chapter 11: Antifragile Joy and Small Pleasures</h3>
<p>Purpose does not require constant intensity. The book’s atmosphere includes delight in small things: tea, conversation, craft progress, seasonal food, a walk at dusk. Small pleasures are not distractions from meaning; they are often the texture of a meaningful life. When people postpone all joy until a big milestone, they may arrive exhausted and unable to feel it. Weaving micro-joys into ordinary days makes perseverance sustainable.</p>
<p>This is especially important in ambitious cultures that moralize grind. Ikigai includes seriousness about contribution, yet it resists the idea that suffering alone proves value. Enjoyment can coexist with discipline. In fact, enjoyment is information: what you delight in practicing is easier to continue for decades—the true timescale of a life philosophy.</p>
<p>Create a short list of inexpensive pleasures that do not sabotage your health or values. Schedule them like medicine. Pair them with purpose when possible: listen to music while crafting, walk while catching up with a friend, cook while listening to a learning podcast. Joy and meaning reinforce each other when designed together.</p>
<p>Small pleasures also train attention, which is the raw material of presence. If you cannot notice tea, birdsong, or craft progress, you will struggle to notice meaning even when it is available. Pleasure practice is attention practice. Keep it ethical and health-aware, and it becomes part of longevity rather than escape from life. Escape pleasures that leave you emptier need different handling—compassion plus boundaries, not more romanticizing.</p>
<p>Create a “minimum joy kit” for hard weeks: three songs, one route outside, one comforting meal you can cook simply, one person you can text without performance. When crisis hits, use the kit without debating whether you deserve it. Deservingness debates are often domestication in another costume. Joy can be a stabilizing right of being human.</p>
<p><strong>Lesson:</strong> Sustain purpose with small, regular pleasures; delight is fuel for a long practice, not a reward you must endlessly delay.</p>

<h3>Chapter 12: Building Your Ikigai Practice</h3>
<p>Bring the ideas into a personal system. Identify one primary activity that currently feels closest to ikigai and give it protected time each week. Strengthen one relationship with a recurring touchpoint. Adopt one eating moderation cue. Add one daily movement ritual. Create one evening shutdown that reduces stress carryover. Five small levers beat one dramatic life overhaul that collapses in a month.</p>
<p>Reassess quarterly. What increased your sense of aliveness? What looked meaningful but felt hollow? Adjust without drama. If your job cannot fully hold your ikigai, let it fund and partially express it while a side practice carries the rest. If your job already aligns, deepen craft and mentorship so the role stays fresh. Keep the question alive: what makes tomorrow worth entering?</p>
<p>Ikigai, as García and Miralles present it, is ultimately a way of inhabiting time. Eat with some restraint. Move often. Belong somewhere. Seek flow. Stay useful. Live enough of today that you do not constantly postpone being alive. Do that long enough, and longevity becomes not merely more years, but more years worth having.</p>
<p>Write a one-page ikigai charter: my current reason to get up, my weekly practice, my people, my movement, my eating cue, my stress boundary, my next experiment. Re-read it monthly. Change one line when life changes. Keep the page short so you will use it. Length is not depth. Finally, remember the emotional tone of the book: curious, gentle, practical, and hopeful without naivety. You are allowed to pursue a long life that feels good on ordinary Wednesdays, not only impressive on paper. That is ikigai as lived philosophy—reason enough, again and again, to enter the morning.</p>
<p>If you take only one action from this summary, schedule your most meaningful activity within the next seven days and protect it like medicine. Knowledge without contact will not change your mornings. Contact will.</p>
<p>Keep the tone kind toward yourself during the search. People who treat purpose-finding as another exam recreate anxiety rather than aliveness. Experiment lightly, keep what warms you, release what does not, and return to morning with something worth doing—however modest—already waiting.</p>
<p><strong>Lesson:</strong> Turn ikigai into a simple weekly practice of purpose, people, moderation, movement, and presence—then recalibrate as life changes.</p>',
  duration_minutes = 25,
  cover_image_url = 'https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg',
  short_description = 'García and Miralles on the Japanese idea of ikigai — a reason for being — and habits linked to longevity, flow, and joyful purpose.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'Ikigai';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'Ikigai');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('What does ikigai roughly mean?', 'A strict diet only', 'A reason for being / reason to get up', 'A type of martial art', 'A financial product', 'B', 1),
  ('What eating principle is associated with Okinawan longevity in the book?', 'Eat until painfully full', 'Hara hachi bu — stop around 80% full', 'Skip all vegetables', 'Only eat once a week', 'B', 2),
  ('How is flow related to ikigai?', 'Flow means constant stress', 'Absorbing challenge-skill balance reveals and fuels meaningful engagement', 'Flow requires doing nothing', 'Flow is only for athletes', 'B', 3),
  ('What do the authors suggest about retirement?', 'Stop all activity immediately', 'Stay active with purpose rather than abandoning contribution', 'Never leave a job', 'Purpose only exists at work', 'B', 4),
  ('Which is one of the ten rules of ikigai?', 'Fill every minute with hustle', 'Live in the moment / follow your ikigai', 'Avoid friends to stay focused', 'Never go outside', 'B', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'Ikigai';
