UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Two fathers, two money philosophies</h2>
<ul><li>Poor Dad emphasizes job security, academic credentials, and living within a salary.</li><li>Rich Dad emphasizes financial education, investing, and building assets that generate income.</li></ul>
<h2>2. Assets put money in; liabilities take it out</h2>
<ul><li>Kiyosaki’s simple test: does this put money in your pocket or take money out?</li><li>Many “prizes” of middle-class life behave like liabilities when they drain cashflow.</li></ul>
<h2>3. Escape the rat race with cashflow thinking</h2>
<ul><li>The rat race is earning, spending, and needing to earn again forever.</li><li>Build assets until passive income covers expenses.</li></ul>
<h2>4. Mind your own business</h2>
<ul><li>Your job is your profession; your business is your asset column.</li><li>Keep buying assets even while you work for a paycheck.</li></ul>
<h2>5. Financial literacy is a four-part skill set</h2>
<ul><li>Accounting, investing, markets, and law work together.</li><li>Corporations and legal structures can be tools of the financially literate.</li></ul>
<h2>6. Work to learn, then make money work</h2>
<ul><li>Seek skills over short-term pay when building capability.</li><li>Master fear and desire so emotion does not sabotage investing discipline.</li></ul>

<h1>PART 2 — RICH DAD POOR DAD</h1>
<h2>A 28-Minute Read Summary</h2>

<h3>Chapter 1: Two Dads, Two Money Scripts</h3>
<p>Robert Kiyosaki frames Rich Dad Poor Dad as a contrast between two father figures. Poor Dad — his highly educated biological father — represents the conventional path: study hard, get a secure job, save, and avoid financial risk. Rich Dad — the entrepreneurial father of a friend — represents another path: learn how money works, acquire assets, and use financial intelligence to create options.</p>
<p>The point is not that education is worthless or that every employee is “poor.” The point is that many people inherit a money script that stops at earning a salary. They become skilled professionals yet remain financially fragile because their education never included cashflow, investing, or the difference between assets and liabilities. Rich Dad’s script treats money as a subject you study for life.</p>
<p>Notice your own inherited lines. “Play it safe.” “Money is scarce.” “Investing is gambling.” “Someone else will handle finances.” Scripts feel like facts until you question them. Replace reflexive statements like “I can’t afford it” with curiosity: “How can I afford it?” That shift does not mean reckless spending; it means training your mind to solve for value creation instead of shutting down.</p>
<p>Write the two scripts side by side for your life: job-only thinking versus asset thinking. Where do you still seek only raises, and where could you also build something that pays you when you are not trading hours? The book begins as autobiography and quickly becomes a mirror.</p>
<p>Kiyosaki’s two-dad device is pedagogical, not a claim that every rich person is wise or every employee is foolish. Plenty of high earners are asset-poor, and plenty of modest earners build quiet wealth through thrift and investing. Use the contrast as a thinking tool: which advice trains dependency on a paycheck alone, and which advice trains ownership and literacy?</p>
<p>If your household has conflicting money scripts, make them explicit in a calm conversation. One partner may equate safety with cash in the bank; the other may equate safety with cashflowing assets. Without a shared language, every investment talk becomes a fight about identity. Rich Dad Poor Dad gives couples a vocabulary — asset, liability, cashflow — that can lower the temperature.</p>
<p>Re-read advice you receive through the two-dad filter. ‘Max out the raise and upgrade the car’ is a Poor Dad celebration of earned income display. ‘Max the raise and buy assets’ is a Rich Dad allocation rule. Same raise, different future. Literacy is often just a better default rule.</p>
<p>If you grew up without any financial conversation, you are not behind forever — you are at chapter one. Begin with definitions, not derivatives. Asset, liability, cashflow, and rat race are enough to change behavior this month. Complexity can wait until the basics are habits.</p>
<p><strong>Lesson:</strong> Examine the money philosophy you inherited — job security alone is not the same as financial intelligence.</p>

<h3>Chapter 2: The Rich Don’t Work for Money Alone</h3>
<p>One of Rich Dad’s early lessons is that fear and desire drive most people’s financial behavior. Fear of not paying bills pushes them into jobs; desire for lifestyle upgrades pushes them to spend raises. The cycle keeps people working for money without learning how to make money work for them.</p>
<p>Kiyosaki argues that emotions are normal, but being controlled by them is expensive. When fear dominates, people cling to a paycheck even when they could learn investing skills gradually. When desire dominates, they celebrate income increases by increasing expenses, resetting the trap. Financial education is partly emotional education: pause between feeling and financial action.</p>
<p>Practical application: when you feel money fear, name it, then take one literacy action — read a statement, calculate cashflow, or study one investment type — instead of only working more hours by default. When you feel lifestyle desire, insert a delay and ask whether the purchase strengthens or weakens your asset column. Raises should preferentially fund assets until your foundation is strong.</p>
<p>This chapter also reframes “working for money.” Employment can be a powerful platform while you learn. The mistake is treating the paycheck as the whole game. Use work to fund education and assets, not only consumption.</p>
<p>A practical emotion protocol helps. When a money decision looms, wait long enough to notice whether fear or desire is in the driver’s seat. Write the feeling down. Then write the financial principle that should drive instead: emergency fund first, understand before investing, assets before luxuries. Re-deciding from principles is how you stop being puppeted by mood.</p>
<p>Employers sometimes exploit fear by framing any independence as disloyalty. You can be a high-integrity employee and still mind your asset column. Learning investing after hours is not a betrayal of your team. It is adult stewardship. Rich Dad’s push against pure paycheck dependence is compatible with professionalism at work.</p>
<p>Teach children the fear/desire lesson with allowance experiments: part for spending, part for giving, part for buying small assets or skills. Early practice shrinks adult emotional chaos. Adults can run the same split with payday automation before desire sees the money.</p>
<p><strong>Lesson:</strong> Don’t let fear and desire run your money life — use emotion as a signal, then choose education and assets over pure paycheck dependence.</p>

<h3>Chapter 3: Assets vs Liabilities — The Core Distinction</h3>
<p>Kiyosaki’s most famous teaching is deceptively simple: an asset puts money in your pocket; a liability takes money out. The rich buy assets. The poor and middle class often load up on liabilities that look like assets — most notably a house bought primarily as a status purchase while it consumes cash in mortgage interest, taxes, maintenance, and fees.</p>
<p>Debate about housing is endless, and context matters: a home can be shelter, stability, and sometimes appreciation. Kiyosaki’s cashflow lens still forces a useful question: what does this item do to my monthly pocket? A rental property that produces positive cashflow after expenses behaves like an asset in his framework. A car loan that drains income behaves like a liability. Paper “investments” you do not understand may be speculation dressed as sophistication.</p>
<p>Build a two-column habit. List everything you own and classify by cashflow direction. Be honest. Then set a rule: before major purchases, ask which column grows. Aim to expand assets until income from them matters. This does not forbid enjoyment; it sequences enjoyment after cashflow strength so lifestyle does not permanently outrun freedom.</p>
<p>Teach this distinction to children and partners with plain language. Financial conflict often shrinks when couples share the same definition of winning: growing the asset column, not merely growing spending after every raise.</p>
<p>Apply the asset test to subscriptions, hobbies, and education. A course that increases your earning skill or investing skill can behave like an asset if you use it. A course bought for identity cosplay and never opened behaves like a liability. The same brand of ‘self-improvement’ can land in either column depending on behavior.</p>
<p>Housing deserves nuance. Paying rent is not moral failure, and buying is not automatic wisdom. Run numbers for your market: total costs of ownership versus rent, mobility needs, maintenance risk, and opportunity cost of down payment capital. Kiyosaki’s harsh take on houses as liabilities is meant to jolt status-driven buying. Your job is cashflow honesty, not dogma.</p>
<p>Revisit classifications annually. An asset can become a liability if costs rise and income falls — a rental with endless repairs, a business without margins. The test is living, not a one-time label. Rich Dad’s simplicity works only if you keep applying it to reality.</p>
<p>Share the asset test with teens using their own world: phone plans, sneaker drops, gaming skins, and part-time income. Ask what puts money back versus what only leaves. Early fluency beats adult remediation. Rich Dad’s kid-friendly diagrams exist for a reason — start simple and stay consistent.</p>
<p><strong>Lesson:</strong> Judge purchases by cashflow — assets put money in your pocket, liabilities take money out.</p>

<h3>Chapter 4: Cashflow Patterns and Why Statements Matter</h3>
<p>Rich Dad Poor Dad pushes readers toward cashflow literacy: understanding income statements and balance sheets at a personal level. Income comes in; expenses go out; assets and liabilities sit on the balance sheet and drive future cashflow. Most people watch only their salary and checking balance, missing the pattern that keeps them stuck.</p>
<p>Draw your personal cashflow. Earned income from a job enters, then exits as taxes, debt payments, living costs, and lifestyle spending. If little or nothing is left to buy assets, your financial future remains almost entirely dependent on showing up to work. The rich, in Kiyosaki’s simplified diagrams, route money into assets that generate additional income — business cashflow, dividends, real estate income, royalties — which can then buy more assets.</p>
<p>Do this monthly. Track every recurring outflow. Separate expenses that maintain earning ability from expenses that only inflate image. Automate transfers into accounts earmarked for assets. Even small automatic buys — index funds, extra principal that truly improves your position, education that raises your skill value — begin to change the diagram.</p>
<p>Cashflow thinking also changes career decisions. A higher salary with much higher mandatory expenses may worsen freedom. A moderate salary with aggressive asset building may improve it. The scoreboard is not income bragging rights; it is the direction of your monthly pattern.</p>
<p>Taxes deserve a line on your cashflow map. Many people negotiate gross salary and ignore net reality. Understand withholding, effective rates, and how different income types are treated where you live. Literacy here prevents fake raises — promotions that disappear before they can fund assets.</p>
<p>Use a simple monthly ritual: update a one-page dashboard with income, expenses, debt payments, net worth, and asset income. Trends matter more than perfection. If expense growth outpaces asset growth for three months, intervene. Cashflow diagrams in the book are cartoons with a serious purpose: make the invisible pattern visible.</p>
<p>Include human capital lightly in your map: skills that reliably increase income. Kiyosaki focuses on paper and property assets, but skill cashflow matters on the path. Just do not confuse a job — trading time — with an asset that works without your hours. Keep the categories honest.</p>
<p><strong>Lesson:</strong> Map your personal cashflow monthly and route surplus into assets that create additional income.</p>

<h3>Chapter 5: The Rat Race Explained</h3>
<p>The “rat race” is Kiyosaki’s name for the loop of working to pay bills, then needing to keep working because expenses and liabilities rise with income. Promotions feel like progress, yet the underlying dependency on earned income remains. People get trapped by social pressure, taxes, debt, and the belief that security equals a job title.</p>
<p>Seeing the rat race clearly is liberating because it names the enemy: not work itself, but permanent dependence without an exit ramp. An exit ramp is asset income that covers living costs — sometimes called financial freedom in popular personal-finance language. You may still work, but you work by choice.</p>
<p>Measure your distance from the rat race with a simple ratio: monthly asset income divided by monthly expenses. If the ratio is near zero, you are fully in the race. If it is growing, you are building an exit. Avoid lifestyle creep that resets the ratio every time you earn more. Celebrate raises by raising the asset contribution rate.</p>
<p>Also watch psychological traps: comparing houses and cars, using debt to look rich, and postponing financial education until “someday.” The rat race thrives on delay. Start imperfectly. Tiny assets are still assets. Literacy compounds alongside capital.</p>
<p>The rat race intensifies with social media comparison. Curated lifestyles advertise liabilities as achievements. Counter with private metrics: months of expenses covered by assets, skill milestones, debt elimination dates. Public applause is a terrible CFO.</p>
<p>Some people need the race temporarily — student seasons, early career runway, caregiving years. Shame helps nobody. The goal is to avoid mistaking a temporary sprint for a permanent identity. Keep a written exit hypothesis: what skill, savings rate, and asset type will eventually change the loop?</p>
<p>Name your rat-race number: monthly expenses times a safety factor. That number turns freedom from a vibe into a target. Then reverse-engineer required asset yield and capital. Plans beat wishful quitting stories. Freedom dates without math are daydreams.</p>
<p>Beware ‘golden handcuff’ versions of the rat race: high salary, high fixed costs, little savings rate, and terror of quitting learning time. Run the numbers before upgrading lifestyle after a promotion. The most expensive traps are the comfortable ones.</p>
<p><strong>Lesson:</strong> The rat race is the cycle of working to pay rising bills — weaken it by growing asset income faster than lifestyle expenses.</p>

<h3>Chapter 6: Mind Your Own Business</h3>
<p>“Mind your own business” in this book does not mean ignore your job. It means build and manage your asset column as your real business, even while you are an employee. Your profession is how you earn today; your business is what you own that can earn tomorrow.</p>
<p>People often mind their employer’s business with great skill — improving company profits — while neglecting their own balance sheet. Kiyosaki urges the opposite imbalance over time: be excellent at work, and be equally deliberate about converting part of your pay into assets. That might mean paper assets, real estate, a side enterprise, intellectual property, or other cashflowing holdings appropriate to your knowledge level.</p>
<p>Start by defining your asset business in writing: what you will acquire this year, what skills you need, and what risk limits you will respect. Keep profession and business accounts mentally separate so a good salary does not hide a weak asset column. Avoid premature quitting fantasies; many people build assets fastest while a paycheck covers basics.</p>
<p>Mind-your-own-business thinking also reduces jealousy and status games. The neighbor’s new car is their cashflow story, not yours. Your scoreboard is your assets and the education that supports them.</p>
<p>Mind your own business also means knowing what business you will not enter. Shiny ventures outside your competence are how capital disappears. Draw a circle of competence and expand it deliberately through study and small experiments. Your asset business should match your knowledge growth, not your envy.</p>
<p>Employees can still build ownership mindsets: equity compensation education, retirement account optimization, intellectual property created on the side within legal boundaries, or a tiny rental or paper-asset system. The form varies; the principle does not — grow what you own that can earn.</p>
<p>Separate operating accounts if you have a side venture: personal, profession, and business/asset. Mixing money hides performance. Even a simple spreadsheet separation improves mind-your-own-business clarity. What gets mixed gets mysterious; what gets measured gets managed.</p>
<p>Schedule a monthly ‘board meeting’ with yourself — thirty minutes to review assets, literacy goals, and next purchases. Wear the owner hat deliberately. Employees who never switch hats remain employees in mindset even when they earn well. The meeting makes the role real.</p>
<p><strong>Lesson:</strong> Treat your asset column as your real business — build it steadily outside your day job.</p>

<h3>Chapter 7: Financial Literacy — Accounting and Investing</h3>
<p>Kiyosaki groups financial intelligence into skills, beginning with accounting and investing. Accounting is the ability to read numbers: cashflow, income, expenses, assets, liabilities. Without it, you cannot tell a good deal from a story. Investing is the skill of using money to acquire assets that produce more money — which requires patience, analysis, and continuous learning.</p>
<p>You do not need to become a CPA to benefit. You do need comfort with basic statements and unit economics: What does this cost to own? What does it return after expenses and taxes? How liquid is it? What can go wrong? Investing without accounting is guessing. Accounting without investing is scorekeeping without a game.</p>
<p>Build literacy with a curriculum. Read simple explanations of financial statements. Practice on your household books. Study one asset class deeply enough to understand cashflow drivers before putting meaningful money at risk. Use paper practice or small stakes while learning. Beware tips that skip understanding — “hot tips” are how uneducated capital is transferred to educated capital.</p>
<p>Schedule weekly study like a class you refuse to skip. Financial literacy is not a personality trait; it is accumulated reps. Rich Dad’s promise is not magic deals; it is a mind trained to see opportunities others walk past.</p>
<p>Accounting for investors includes understanding leverage. Debt can amplify returns and losses. Kiyosaki is friendlier to ‘good debt’ used to acquire cashflowing assets than to consumer debt used for lifestyle. Even then, leverage without literacy is dangerous. Know debt service coverage, interest rate risk, and your tolerance for sleeplessness.</p>
<p>Investing skill includes knowing when not to invest. Cash reserves, boring index exposure, and patience are compatible with Rich Dad themes when they are chosen consciously as part of a plan. The enemy is not conservatism; the enemy is financial illiteracy paired with emotional decision-making.</p>
<p>Build a personal investing policy statement: goals, horizon, risk limits, asset types allowed, and rules for adding capital. This document is accounting-plus-investing discipline in one page. It protects you from tips at dinner parties and from your own mood on volatile days.</p>
<p><strong>Lesson:</strong> Build financial literacy starting with accounting and investing skills so you can evaluate deals instead of following tips.</p>

<h3>Chapter 8: Markets and Law — Completing the Literacy Set</h3>
<p>Alongside accounting and investing, Kiyosaki highlights markets and law. Markets means understanding supply, demand, cycles, and the emotional herd. Prices are not only math; they are people. Legal and tax knowledge means understanding how entities, contracts, and rules change outcomes. In his telling, the financially sophisticated use corporate structures and tax rules more effectively than those who earn only as individuals and then wonder why so much income disappears.</p>
<p>This is not a call to shady loopholes. It is a call to learn the real rules of the game played in your country: how businesses are taxed versus wages, how liability protection works, and when professional advice is required. Employees often maximize only job skills while business owners invest in legal and tax education because the returns are obvious.</p>
<p>Practical steps: learn basic market history so booms and busts do not shock you into panic selling. Follow reputable investor education, not hype. For law and tax, take an introductory course or work with a qualified advisor once your situation has complexity — incorporation, rental property, or contracting. Ask questions until structures make sense. Never sign what you do not understand.</p>
<p>Together, accounting, investing, markets, and law form a toolkit. Weakness in one area can undo strength in another. Aim for T-shaped knowledge: broad literacy across all four, deeper skill in the area where you will actually deploy capital.</p>
<p>Market literacy includes humility about forecasts. If anyone speaks with certainty about short-term prices, dial up skepticism. Study long-run behavior of asset classes, inflation, and human cycles of greed and fear. Your edge is behavior and time horizon more often than secret information.</p>
<p>Legal literacy includes contracts you already sign: employment agreements, leases, partnership docs. Read them. Ask what happens if things go wrong. Many ‘money problems’ begin as unread documents. Rich Dad’s insistence on law is really insistence on reading the rules before playing.</p>
<p>Follow one reputable tax-and-law educator for your country each year and take notes on changes. Laws evolve. Yesterday’s cocktail-party tip can become today’s penalty. Rich Dad’s category remains valid; your local implementation must stay current.</p>
<p><strong>Lesson:</strong> Round out financial literacy with markets and legal/tax basics so opportunity and protection work together.</p>

<h3>Chapter 9: Corporations and Financial Tools of the Rich</h3>
<p>Kiyosaki emphasizes that the rich often earn, spend, and invest through corporate structures, while many employees earn and then spend what’s left after taxes. Details vary by jurisdiction, and laws change, so treat this as a conceptual lesson: legal structures can separate personal risk, shape tax timing, and professionalize how money moves.</p>
<p>The deeper point is agency. Financially literate people ask which vehicle best holds an asset, how to manage liability, and how to reinvest business profits into more assets. Financially illiterate people may fear business entities as “for someone else” and thus never learn. Fear of the unknown becomes a tax on possibility.</p>
<p>If you are early stage, do not rush into complex structures you cannot maintain. First master personal cashflow and basic investing. When you have a real business activity, educate yourself and hire competent professionals. Use entities as tools for real operations, not as magical riches machines. Compliance and bookkeeping are part of the price of those tools.</p>
<p>Also separate glamour from substance. A corporation with no assets and no skills is stationery. Skills plus assets plus appropriate structure is power. Rich Dad’s corporate talk is really about taking money education as seriously as career education.</p>
<p>In some countries, the tax and liability differences between earning as an individual and operating a company are significant; in others, less so. Always localize the lesson. The portable insight is to learn incentives: governments and markets reward certain structures and behaviors. Curiosity about incentives is financial intelligence.</p>
<p>Avoid guru versions of this chapter that imply paperwork creates wealth. Customers, margins, and assets create wealth. Paperwork can protect and optimize what is real. If someone sells you a corporation kit as a riches machine, you are the product.</p>
<p>When ready for an entity, interview professionals with prepared questions: liability exposure, tax treatment, bookkeeping burden, and exit rules. If they cannot explain simply, keep looking. You are responsible for understanding the tool you use — delegation is not abdication.</p>
<p><strong>Lesson:</strong> Learn how legal and corporate structures can support assets and risk management — then use them with professional guidance when your situation warrants.</p>

<h3>Chapter 10: Work to Learn — Skills Over Pure Pay</h3>
<p>Another signature idea: work to learn, not merely to earn. Early in a career, choosing roles for skills — sales, marketing, operations, leadership, financial management — can outperform choosing only for the highest immediate paycheck. Skills compound across ventures; a slightly higher salary in a narrow role may leave you fragile if that role disappears.</p>
<p>Kiyosaki’s Rich Dad pushes learning communication, selling, and understanding business systems. Many technically gifted people stay underpaid relative to their potential because they never learn to sell ideas, negotiate, or lead. Sales skill, in this framing, is not sleaze; it is the ability to persuade and create exchange — central to every business.</p>
<p>Audit your skill portfolio. Which skills would make you valuable in multiple industries? Which gaps block your asset goals — for example, analyzing deals, managing contractors, or reading statements? Design your next job move or side project to close a gap. Take the uncomfortable assignment. Volunteer for the project that teaches management or customer acquisition.</p>
<p>Be pragmatic about bills. “Work to learn” does not mean ignore rent. It means optimizing the learning rate of your working years, especially in your twenties and thirties, while still funding your asset column. The combination — skills plus assets — is the book’s real wealth engine.</p>
<p>Sales skill deserves special emphasis because it funds every other skill. If you can communicate value, you can raise capital, recruit partners, win customers, and negotiate salaries. People who find sales icky often carry a caricature of manipulation. Ethical sales is diagnosis plus truthful persuasion. Learn it in low-stakes environments.</p>
<p>Map a three-year learning tour: year one communications and selling, year two leadership and financial statements, year three a specialty tied to the assets you want to own. Jobs become classrooms. Pay still matters — choose the best ‘school’ you can afford that also pays tuition in skills.</p>
<p>Seek stretch assignments that put you in front of customers or financial decisions. Internal projects that only polish slides rarely teach Rich Dad skills. Volunteer for budget ownership, pricing experiments, or partnerships. Learning velocity compounds like capital.</p>
<p>If your workplace cannot teach a needed skill, buy the class, find a volunteer organization, or start a tiny project that forces the skill. Waiting for permission is a Poor Dad habit dressed as politeness. Learning agility is part of minding your own business.</p>
<p><strong>Lesson:</strong> Choose work that builds high-transfer skills — especially sales, leadership, and financial management — not only higher short-term pay.</p>

<h3>Chapter 11: Mastering Fear, Desire, and Risk</h3>
<p>Fear of losing money keeps people in pure savings mode or speculative freezes; desire for quick riches pushes them into bubbles and tips. Kiyosaki insists both emotions must be managed. Courage without education is recklessness. Education without courage is inert knowledge. Progress requires both study and action at a size you can survive if wrong.</p>
<p>Create personal risk rules. Never invest in what you do not understand. Diversify enough that one mistake is not fatal. Start small to gain experience. Separate emergency savings from investment capital so market drops do not force panic liquidations of long-term assets. Define “enough lifestyle” so desire does not constantly raise your expense floor.</p>
<p>Practice emotional drills. When markets fall, follow a written plan instead of social media. When a flashy purchase tempts you, wait seventy-two hours and recalculate cashflow impact. When fear says “never invest,” respond with a learning plan and a tiny first step, not all-or-nothing thinking.</p>
<p>Community matters. Surround yourself with people who talk about assets and education more than status purchases. Isolation makes fear louder and desire easier to rationalize. Rich Dad’s circle was part of the curriculum.</p>
<p>Fear often disguises itself as prudence. Ask whether your caution is calibrated to facts or frozen by embarrassment about not knowing enough. The remedy for ignorance-fear is a curriculum and a mentor, not permanent avoidance. Desire disguises itself as opportunity. Ask whether you understand the downside in writing.</p>
<p>Use position sizing as emotional technology. Investing an amount that would ruin you makes every tick of the market a panic event. Investing an amount you can survive lets intelligence stay online. Rich Dad’s bold tone still requires adult risk management.</p>
<p>Keep a mistake log without self-contempt: what you misunderstood, what rule you will add, what you will never repeat. Fear shrinks when mistakes become curriculum. Desire shrinks when you force every hot deal through your written checklist and watch most of them fail the test.</p>
<p><strong>Lesson:</strong> Train yourself to act with educated courage — size risks so fear and greed cannot sabotage long-term asset building.</p>

<h3>Chapter 12: Making Money Work for You</h3>
<p>The destination of the book’s lessons is a life where money works for you through assets, while you retain the option to work for purpose and growth. That does not require billionaire status. It requires a repeated pattern: earn, control expenses, buy assets, reinvest returns, expand literacy, and avoid liabilities that pretend to be success.</p>
<p>Build a one-page plan. List current monthly expenses. List current asset income. Set a target date for a meaningful ratio improvement. Identify the next asset to learn and the next skill to acquire. Automate contributions. Review quarterly. Adjust as laws, markets, and family needs change. Keep ethics intact — wealth built by value creation beats shortcuts that destroy trust.</p>
<p>Remember the spirit of the two dads. Poor Dad’s values — education, responsibility, integrity — need not be discarded. They can be paired with Rich Dad’s financial literacy so responsibility includes cashflow mastery. The goal is not to mock employment; it is to refuse financial helplessness.</p>
<p>Start where you are. Read your numbers this week. Cut one liability path. Fund one asset seed. Learn one concept deeply. Money begins to work for you when your habits stop working exclusively for short-term comfort.</p>
<p>Making money work for you is a multi-decade craft. Expect boring compounding, occasional mistakes, and ongoing study. Revisit the asset/liability test after every major life change: marriage, children, moves, career switches. The definitions stay simple; your application gets more sophisticated.</p>
<p>Close the loop with teaching. Explain cashflow to a child or friend in plain language. Teaching reveals what you do not yet understand and embeds the habit of literacy. Kiyosaki’s book endures because it converts money from taboo into a subject. Your job is to keep studying after the slogans fade — and to keep buying assets that honestly put money back in your pocket.</p>
<p>Annual review ritual: update cashflow diagrams, rebalance education goals, check progress toward asset-income ratio, and set one literacy theme for the year — for example ‘rental underwriting’ or ‘business reading.’ Rich Dad Poor Dad is a starting map. Your yearly review is how the map becomes territory.</p>
<p>Measure success by options created: the option to take a sabbatical, help family, decline a toxic client, or fund a new venture. Money working for you shows up as choice. Choice is the quiet wealth Rich Dad points toward beyond flashy toys.</p>
<p><strong>Lesson:</strong> Make money work for you by repeatedly converting earnings into understood assets until asset income meaningfully supports your life.</p>',
  duration_minutes = 28,
  cover_image_url = 'https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg',
  short_description = 'A guide to financial literacy and wealth building — the principles that separate assets from liabilities and how to make money work for you.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'Rich Dad Poor Dad';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'Rich Dad Poor Dad');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('What is the main difference between an asset and a liability according to Rich Dad?', 'Assets cost money, liabilities make money', 'Assets put money in your pocket, liabilities take money out', 'Assets are investments, liabilities are expenses', 'There is no difference', 'B', 1),
  ('What does "Mind Your Own Business" mean in the context of the book?', 'Focus on your job and career', 'Build assets outside of your profession', 'Avoid talking about money', 'Start your own company immediately', 'B', 2),
  ('According to Rich Dad, what should you prioritize when it comes to money?', 'Working harder for a higher salary', 'Learning financial literacy and building assets', 'Avoiding all risks', 'Saving everything you earn', 'B', 3),
  ('What is the "Rat Race" that Kiyosaki describes?', 'A competitive job market', 'The cycle of working to pay bills, which keeps you working', 'A financial investment strategy', 'A type of business competition', 'B', 4),
  ('What mindset shift does Rich Dad recommend instead of saying "I can''t afford it"?', 'Accept that you can''t afford it', 'Ask "How can I afford it?"', 'Borrow money to buy it', 'Wait until you have more money', 'B', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'Rich Dad Poor Dad';
