UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Wealth vs money vs status</h2>
<ul><li>Seek assets that earn while you sleep; status games are zero-sum distractions.</li></ul>
<h2>2. Specific knowledge</h2>
<ul><li>Build unique, hard-to-train knowledge that feels like play to you.</li></ul>
<h2>3. Accountability and ownership</h2>
<ul><li>Put your name on outcomes; seek equity so upside is not capped by hours.</li></ul>
<h2>4. Leverage — labor, capital, code, media</h2>
<ul><li>Multiply judgment; prefer permissionless leverage when it fits your craft.</li></ul>
<h2>5. Judgment and long-term games</h2>
<ul><li>Clear thinking under skin-in-the-game responsibility becomes extremely valuable.</li></ul>
<h2>6. Happiness as a skill</h2>
<ul><li>Peace, presence, desire-management, and meditation matter as much as wealth.</li></ul>
<h2>7. Compound everything</h2>
<ul><li>Skills, trust, products, and calm all compound when you stay long-term.</li></ul>
<h1>PART 2 — THE ALMANACK OF NAVAL RAVIKANT</h1>
<h2>A 27-Minute Read Summary</h2>
<h3>Chapter 1: A handbook for wealth and happiness</h3>
<p>The Almanack of Naval Ravikant (2020), compiled by Eric Jorgenson, gathers entrepreneur and investor Naval Ravikant’s tweets, podcast interviews, and talks into a structured handbook. It is not a memoir and not a conventional business textbook. It is a compressed philosophy of how to create wealth and how to create happiness — treated as two parallel, learnable crafts rather than as lottery outcomes or personality traits you either won at birth or did not.</p>
<p>Jorgenson’s contribution is editorial architecture. Naval’s ideas had already circulated widely online as viral fragments; the Almanack clusters them so a reader can study them as a system. Two arcs dominate: an external arc about earning freedom through skills, leverage, and ownership, and an internal arc about peace of mind, desire, and presence. Ambitious people often chase the first while neglecting the second, then wonder why arrival feels empty. The book insists both dashboards matter.</p>
<p>The tone is aphoristic. Many lines sound like maxims because they began as tweets. That compression is a feature if you reread slowly, and a trap if you skim for slogans to post. The useful approach is to treat each idea as a practice — specific knowledge, leverage, judgment, long-term games, meditation — then cycle back as your career stage and mental habits change. What you need at twenty-five when you are hunting skill may differ from what you need at forty when you are drowning in status obligations.</p>
<p>Start with a personal audit rather than inspiration theater. Are you primarily collecting status tokens — titles, applause, insider belonging — or building equity in skills and assets? Are you trading time linearly for wages forever, or designing work that can scale beyond your calendar? Are you calm enough to enjoy freedom if you get it, or would a quieter schedule still be filled with mental noise? Those questions frame everything that follows.</p>
<p>Naval’s worldview rewards patience. Compounding needs time, and time needs a mind that can stay the course without constant comparison. The Almanack is less a book to “finish” than a manual to revisit when you are choosing a career bet, a collaborator, a public identity, or a relationship with your own attention. Read it as an operator’s philosophy, not as entertainment.</p>
<p>If you read only for inspiration, you will leave with quotes. If you read for redesign, you will leave with experiments: one career bet toward ownership, one cut to a status game, one daily practice for peace. The Almanack rewards that operator stance.</p>
<p>Keep the Almanack nearby as a corrective when envy spikes. Status spikes are loud; ownership is quiet. When you feel behind because someone else was applauded, reread the wealth-versus-status distinction before you redesign your life around their scoreboard.</p>
<p><strong>Lesson:</strong> Treat wealth and happiness as parallel skills — study them as a system of leverage and peace, not as random luck.</p>
<h3>Chapter 2: Wealth, money, and status are different games</h3>
<p>Naval’s most clarifying distinction separates wealth, money, and status. Wealth is assets that earn while you sleep — businesses, equity stakes, products, investments, intellectual property, systems that continue producing value when you are offline. Money is the medium you use to transfer time and wealth; it is useful, measurable, and necessary for exchange, but holding cash is not the same as owning productive assets. Status is your rank in a social hierarchy — who is above whom in prestige, attention, coolness, or institutional belonging.</p>
<p>Status games are often zero-sum. For someone to rise in a hierarchy, someone else may feel lowered. That dynamic breeds envy, politics, performative signaling, and anxiety. Wealth creation, by contrast, can be positive-sum: a product that helps thousands can create value without requiring someone else’s failure as the fuel. The book repeatedly warns ambitious people not to confuse applause with freedom. You can win status and still feel trapped by appearances; you can build quieter wealth and feel free to allocate your days.</p>
<p>This distinction changes career strategy. Chasing titles, viral moments, or insider belonging can feel like progress while leaving you with no equity and a fragile identity that needs constant feeding. Building a skill that compounds, a product that distributes, or ownership in something productive may look slower on social media and pay better over a decade. Naval’s counsel is not anti-ambition; it is anti-confusion about the scoreboard you are actually optimizing.</p>
<p>Money anxiety often comes from confusing cash flow with ownership. A high salary can still be a high-end rental of your time. If expenses rise with income and you own nothing that works when you stop, you have money motion without wealth. Lifestyle inflation turns raises into golden handcuffs. The Almanack pushes readers toward ownership thinking: What can I create or own that continues working after I step away from the desk?</p>
<p>Practically, rewrite goals in asset language. Instead of “become impressive,” ask “what specific knowledge and leverage can I own?” Instead of “get more followers,” ask “what audience, product, or equity creates durable optionality?” Status may arrive as a side effect of real creation; treating status as the main goal usually corrupts taste, ethics, and joy in the work itself.</p>
<p>A simple weekly review helps: list income sources, then mark which ones require your active hours versus which ones can earn without your constant presence. Increase the second column over years. That is wealth thinking made concrete, not motivational.</p>
<p>Teach children and teammates the same vocabulary. Praise creation and ownership more than applause. Cultures that only reward visible status train people to optimize theater. Cultures that reward shipped value train people to compound.</p>
<p><strong>Lesson:</strong> Pursue wealth-creating assets and skills; do not confuse cash-in-the-moment or social rank with freedom.</p>
<h3>Chapter 3: Specific knowledge — play that looks like work</h3>
<p>Specific knowledge is Naval’s central career concept: knowledge that cannot be easily trained into other people through a standard curriculum. It often sits at the edge of your curiosity and unique life path. It feels like play to you and looks like work to others. If society can mass-produce people to do a task via school or a short bootcamp, that skill is less likely to be specific — and less likely to command outsized, enduring returns once supply catches up.</p>
<p>Specific knowledge is not identical to a prestigious degree, though education can help. Credentials signal trainable competence; specific knowledge is the odd combination of taste, timing, lived experience, obsession, and judgment that makes you uniquely useful. Examples might include an unusual blend of technical depth and storytelling, industry intuition earned inside a niche for years, creative taste that cannot be checklisted, or the ability to see distribution opportunities others miss.</p>
<p>You find it by following genuine interest deeply rather than by reverse-engineering only “what pays right now.” Authenticity matters because faking interest collapses under the years of practice required. Naval’s point is not a poster that says “follow your passion” as lifestyle branding. It is: notice what absorbs you, keep compounding skill there, ship work, and let the market discover economic value later. Reading widely, building in public, apprenticing under reality, and combining skills across domains are classic paths into rarity.</p>
<p>Specific knowledge pairs with iteration. You rarely identify it in a weekend brainstorming session. You try projects, notice what comes unusually easy, notice what others already request from you, and double down for years. The person who keeps switching to whatever is generically trendy often never compounds far enough to become scarce. Trends are crowded; your weird intersection is less crowded.</p>
<p>Map skills that feel like play and that others already ask you for help with. Design the next decade around deepening that intersection rather than collecting every fashionable credential. Specific knowledge is a long game played with authentic obsession and repeated contact with reality.</p>
<p>When stuck choosing a direction, ask which problems you solve for free because curiosity pulls you — then ask who already pays for adjacent solutions. Specific knowledge often lives where unpaid fascination meets unpaid market demand waiting for a better package.</p>
<p>Specific knowledge often looks uneven on a resume. That unevenness is fine. A coherent story — “I combine X and Y to solve Z” — matters more than a generic stack of credentials everyone else also has. Write that story and test it against real demand.</p>
<p><strong>Lesson:</strong> Build specific knowledge through authentic obsession — unique, hard-to-train skill that feels like play to you.</p>
<h3>Chapter 4: Accountability, equity, and putting your name on it</h3>
<p>Naval links specific knowledge to accountability: taking responsibility under your own name. When outcomes are attached to you, reputation becomes an asset. People who are uniquely good and personally responsible become magnets for opportunity, capital, introductions, and trust. People who hide in committees, avoid ownership, or optimize only for looking busy rarely compound in the same way, because nobody knows what they can be counted on to deliver.</p>
<p>Accountability is uncomfortable because failure becomes personal. That is also why it pays. Markets and teams pay premiums for people who will own a problem end-to-end. Internally, accountability clarifies feedback: you learn faster when results cannot be blamed on fog. Externally, a track record of kept promises becomes leverage of its own — the kind of social capital that opens doors money alone cannot buy quickly.</p>
<p>Ownership connects to equity. Trading time for a wage can be a valid and honorable stage of life, especially while learning. Naval’s wealth path, however, emphasizes capturing a share of what you create — equity in a business, ownership of a product, royalties, upside participation, or other residual claims. Without some form of ownership, your upside stays capped by hours and by someone else’s budget. With ownership, a good decision or product can keep paying after the workday ends.</p>
<p>This does not mean everyone must found a venture-scale startup tomorrow. It means thinking like an owner wherever you are: take projects you can be proud to sign; negotiate for upside when you create outsized value; build personal products on the side if your job cannot offer equity yet; document proof of work so your reputation travels with you. The mindset shift is from “How do I get paid for this hour?” to “How do I create something that keeps working?”</p>
<p>Reputation compounds slowly and can be destroyed quickly. Naval’s long-term framing implies ethical consistency: short-term tricks that damage trust are expensive in a leveraged career. Play games you can still respect yourself for playing in ten years.</p>
<p><strong>Lesson:</strong> Attach your name to outcomes and seek ownership — accountability and equity turn skill into compounding assets.</p>
<h3>Chapter 5: Leverage — labor, capital, code, and media</h3>
<p>Leverage multiplies the output of your judgment. Naval describes classic forms: labor leverage (people working with you), capital leverage (money amplifying decisions), and newer, more permissionless forms: code and media. Labor and capital historically required others’ approval — hiring teams, raising funds, getting onto a balance sheet. Code and media can often be started without a gatekeeper’s blessing: write software or create content that serves thousands while you sleep.</p>
<p>That shift reshapes modern careers. A person with specific knowledge can publish ideas, ship tools, or build audiences without waiting for institutional permission. The marginal cost of copying software or distributing digital media can be near zero, so one unit of creative work can reach enormous scale. That is why Naval elevates products and content alongside traditional paths of employment and management.</p>
<p>Without leverage, inputs stay roughly linear with time: more hours, more output, then a hard stop when you sleep or burn out. With leverage, judgment becomes extremely valuable because one clear decision can scale across users, capital, or attention. Busywork looks productive in the short term but does not scale. High-leverage work looks like designing systems, allocating capital wisely, writing code that runs without you, or creating media that teaches, entertains, or sells while you are offline.</p>
<p>Labor leverage still matters — teams multiply founders — but it brings management cost, coordination overhead, and permission constraints. Capital leverage can create wealth quickly and also destroy it through bad judgment or fragile debt. Code and media are not automatically easy; they still require craft, taste, and iteration. They are simply more available to individuals willing to learn and ship without asking first.</p>
<p>Ask where your judgment can be applied once and benefit many. Move career effort toward products, content, capital allocation, or systems that scale, rather than only selling hours. Combine specific knowledge with the form of leverage that fits your skills, temperament, and ethics.</p>
<p>Start permissionless leverage with a small shippable unit: a useful script, a clear essay, a template, a tool. Scale follows proof. Waiting for a perfect platform often hides fear of shipping. Leverage begins at version one.</p>
<p><strong>Lesson:</strong> Seek leverage — especially permissionless code and media — so judgment scales beyond your calendar.</p>
<h3>Chapter 6: Judgment under leverage, and why thinking clearly pays</h3>
<p>In a leveraged world, judgment is the scarce resource. If your decisions can be multiplied by capital, code, or audience, the quality of those decisions dominates the quantity of your hustle. Naval emphasizes clear thinking, understanding incentives, and avoiding self-deception. Reading widely — especially foundational science, the mathematics of compounding, philosophy, biographies of builders, and timeless texts — is presented as infrastructure for judgment, more valuable than most news consumption that optimizes for arousal.</p>
<p>Judgment improves when you understand first principles rather than collecting fashionable opinions. It improves when you can model second-order effects: what happens after the obvious happens. It improves when you have skin in the game, because reality grades your predictions without flattery. People who only perform intelligence in conversation often fail when outcomes are personal and irreversible.</p>
<p>Naval also stresses long-term games with long-term people. Trust multiplies collaboration; distrust taxes everything with contracts, politics, and hedged effort. Compound interest applies to relationships and reputation as much as to money. Short-term extraction from partners may win a quarter and lose a decade of compounding opportunities. Choosing collaborators who keep promises and share upside is itself a high-leverage judgment skill.</p>
<p>Patience appears as a wealth skill. Many outstanding curves stay flat for years before bending upward. Impatience pushes people into status hustles, premature quitting, or leverage they do not understand. Clear thinkers can endure boring competence longer than ego comfortably allows — and boring competence is often where compounding hides.</p>
<p>Upgrade judgment weekly: read something foundational, review one past decision’s real incentives and outcomes, and choose collaborators who play long-term games. Treat thinking quality as a primary career asset, not a soft accessory to visible hustle.</p>
<p>Keep a decision journal for large bets: what you believed, what incentives were present, what happened. Over years the journal trains humility and pattern recognition better than motivational podcasts. Judgment is a craft with feedback loops.</p>
<p><strong>Lesson:</strong> Invest in judgment and long-term trust — leveraged careers amplify thinking quality above raw effort.</p>
<h3>Chapter 7: Productize yourself — building a personal monopoly</h3>
<p>A practical synthesis of Naval’s career advice is often summarized as: productize yourself. Combine specific knowledge, accountability, and leverage so that “you” become a scarce product — not a generic labor unit competing only on hours and compliance. That does not mean turning your entire personality into a brand stunt or performing intimacy for algorithms. It means packaging what is uniquely valuable about your judgment into forms that scale: a company, a product line, a body of work, a reputation for solving a certain class of problems unusually well.</p>
<p>Productizing yourself usually requires saying no to generic paths that keep you interchangeable. If your calendar is filled with work anyone competent could do, you are easier to replace and harder to leverage. If your calendar is filled with work that uses your rare combination of skills, you become harder to copy. The market pays for scarcity plus usefulness. Being weird in a useful way is a feature.</p>
<p>This path favors builders over pure credential collectors. Credentials can open doors; products and proof open more doors later. Shipping imperfect work, iterating publicly, and learning from users or clients accelerates specific knowledge. Waiting until you feel fully ready often means never becoming rare, because readiness is a moving target designed by fear.</p>
<p>There is an ethical edge. Productizing yourself without integrity becomes manipulation and eventually collapses. Naval’s long-term framing implies that the product must actually help; reputation is the distribution channel that compounds. Shortcuts that burn trust destroy the asset you are trying to build, especially in permissionless media where memory is long and screenshots travel.</p>
<p>Define a one-sentence personal monopoly: the problem you solve, for whom, with what unique angle. Then align learning, projects, and leverage around that sentence for years. Adjust as reality teaches you, but avoid reinventing your entire identity every season for novelty’s sake.</p>
<p><strong>Lesson:</strong> Productize your specific knowledge with accountability and leverage — become a scarce, useful package rather than interchangeable labor.</p>
<h3>Chapter 8: Happiness as peace, not endless pleasure</h3>
<p>Naval’s happiness thread is as central as wealth. He describes happiness less as continuous pleasure and more as peace — a default state with less internal conflict and less war against the present. Desire, especially for what you cannot presently affect, contracts unhappiness into the now. Managing desire is therefore a happiness skill, not merely a monk’s luxury or a consolation prize for people who “failed” at ambition.</p>
<p>This reframing matters for ambitious people. External success can increase desires faster than it satisfies them. A bigger house reveals a bigger neighborhood; a promotion reveals a higher ladder; a follower count reveals another creator ahead of you. Without an internal practice, wealth becomes a treadmill with nicer scenery. Naval’s point is not anti-goal; it is anti-unconscious craving. Choose goals deliberately, then refuse to let every unmet want own your nervous system.</p>
<p>Presence matters. The mind’s habit of living in regret and anxiety steals the only life you actually inhabit — this moment. Much suffering is mental time travel: rehearsing past injuries or future threats while the present remains workable. Happiness practice includes returning attention to now, repeatedly, without needing circumstances to become perfect first. You can plan for the future as a tool without living emotionally trapped inside imagined futures.</p>
<p>Gratitude and acceptance appear as practical tools rather than greeting-card sentiments. Acceptance is not passivity about action; it is refusing to add secondary suffering through resistance to reality you cannot instantly change. You can accept that a problem exists and still work on it skillfully. What Naval argues against is the constant war with the present that makes even objectively good lives feel insufficient.</p>
<p>Define happiness operationally for yourself: fewer needless desires, more present attention, more peace between thoughts. Then treat that definition as trainable rather than as a mood that arrives only when metrics hit a round number.</p>
<p><strong>Lesson:</strong> Train happiness as peace and desire-management — not as endless pleasure or status arrival.</p>
<h3>Chapter 9: Meditation, health, and the quiet mind</h3>
<p>Meditation, for Naval, is a practical tool to observe thoughts without being owned by them. The goal is not mystical theater or social performance; it is training a gap between stimulus and reaction so peace becomes a skill. Sitting quietly, watching the breath or simply noticing mental chatter, reveals how much of “you” is automatic narrative — old fears, status scripts, and rehearsed complaints. Over time, identification with every thought can loosen, and choice returns.</p>
<p>Consistency beats intensity. A daily practice, even short, compounds more than rare heroic retreats followed by months of neglect. Naval’s broader point is that the mind can be trained like the body. People accept gyms for muscle and somehow expect mental peace to arrive without practice when circumstances finally cooperate. Meditation is one method; walks without phones, single-tasking, and deliberate silence can support the same capacity for non-reactivity.</p>
<p>Health basics — sleep, exercise, diet — are cognitive infrastructure. Poor sleep destroys judgment; sedentary life dulls mood; junk fuel increases friction and inflammation that the mind experiences as fog or irritability. Freedom includes the capacity to think clearly. A wealthy, busy, status-anxious life can still be miserable if the body and mind never recover. White space on the calendar is not laziness; it is maintenance of the instrument that makes all leverage possible.</p>
<p>Naval also links freedom to reducing unnecessary obligations and status performances. Every commitment is a claim on future attention. High agency includes pruning. The quiet mind is easier when your life is not oversubscribed with games you do not actually value but are afraid to exit.</p>
<p>Install a non-negotiable daily quiet block — meditation or silent sitting — and protect sleep and movement as seriously as you protect income-producing work. Peace is not the prize after success; it is part of the operating system that makes success usable.</p>
<p><strong>Lesson:</strong> Practice meditation and protect health — a quiet, rested mind is required to use freedom well.</p>
<h3>Chapter 10: Reading, learning, and foundations over noise</h3>
<p>Naval’s learning philosophy favors foundations over fashion. Reading widely in science, philosophy, economics of incentives, biographies of builders, and timeless works builds mental models that transfer across domains. Most news and social feeds optimize for arousal, tribal identity, and novelty, not understanding. A person who understands compounding, incentives, probability, and human nature can evaluate new claims faster than a person who only tracks headlines and hot takes.</p>
<p>He often emphasizes learning that sticks through interest. Forced study for status produces brittle knowledge that evaporates after the exam or the interview; curious reading produces specific knowledge over years because attention is genuine. The advice to read what you love until you love to read supports long compounding. Depth in a few great books can beat shallow coverage of many mediocre ones that merely make you feel “informed.”</p>
<p>Learning also happens by building. Theories untested by shipping remain decorative. Naval’s builder bias implies that projects are laboratories for judgment. You learn pricing, taste, distribution, negotiation, and your own psychology by creating things that can fail in public. Combine reading with making; otherwise you risk becoming a collector of elegant opinions with no contact with reality.</p>
<p>In a world of infinite content, attention is the real scarce input. Choosing what not to consume is part of becoming smarter. Curate inputs the way an investor curates a portfolio: high expected value, low junk, long hold periods for ideas that keep paying dividends in clearer decisions.</p>
<p>Replace one hour of low-quality feed scrolling with foundational reading or deliberate skill practice. Over a year, that swap compounds into a different mind — and a different career ceiling — without requiring a dramatic life overhaul.</p>
<p><strong>Lesson:</strong> Prefer foundational learning and building over noisy feeds — mental models and shipped projects compound judgment.</p>
<h3>Chapter 11: Long-term games and compound everything</h3>
<p>If there is a master metaphor in Naval’s thinking, it is compounding. Capital compounds. Skills compound. Trust compounds. Content libraries compound. Fitness compounds. Peace compounds when practiced. Networks of high-integrity people compound. The opposite — constantly resetting for novelty, burning reputation for short wins, quitting before curves bend, hopping identities for dopamine — destroys the only force that makes ordinary daily effort extraordinary over time.</p>
<p>Long-term games require long-term people. Choose partners, friends, employers, and audiences you can imagine still respecting in ten years. Avoid environments that reward betrayal, empty signaling, or permanent short-termism. The tax of low-trust systems is enormous: everything needs contracts, politics, and hedged effort. High-trust systems feel almost unfairly productive because energy goes into creation instead of defense.</p>
<p>Long-term games also require identity flexibility without value collapse. You can change tactics — products, jobs, cities, tools — while keeping a stable ethic: create value, tell the truth, keep promises, improve judgment, protect peace. People who reinvent morals every quarter cannot compound trust, because nobody knows which version of them will show up next.</p>
<p>Impatience is the silent killer of compounding. Social media shows compressed highlight reels of others’ decade-long work. Comparing your year one to someone’s year fifteen produces false urgency and reckless leverage. Naval’s path often looks slow in the middle and sudden at the end because compounding is nonlinear. The middle is where most people quit and restart somewhere crowded.</p>
<p>Pick a few compounding engines and refuse to abandon them lightly: a craft, a body of work, a savings or investment habit, a meditation practice, a set of relationships. Review yearly, not hourly. Let time become an ally instead of an enemy you try to outrun with frantic pivots.</p>
<p>Protect compounding from interruption. Every dramatic restart has a cost: lost trust, lost skill depth, lost audience memory. Some restarts are necessary; many are ego escapes. Before quitting a compounding engine, ask whether you are bored of the work or bored of not being admired for it yet.</p>
<p><strong>Lesson:</strong> Play long-term games with long-term people — compounding needs time, trust, and the patience to stay.</p>
<h3>Chapter 12: Integrating wealth and peace into one life</h3>
<p>The Almanack’s synthesis is that wealth without peace is a treadmill, and peace without agency can slide into passivity or spiritualized avoidance. Naval’s ideal combines specific knowledge, accountability, and leverage to create financial freedom, with a mind trained toward gratitude and presence so freedom is actually felt. External dashboards and internal dashboards must both be watched, or one will sabotage the other.</p>
<p>Practical integration looks like this: choose work that compounds skill; build products or content when you can; keep ethics and reputation clean; avoid status addiction; protect health; meditate or sit quietly; reduce needless desires; play long-term games with people who do the same. You do not need a billionaire outcome to use the philosophy. Even modest ownership plus a calmer mind can transform the felt quality of a life more than another status bump.</p>
<p>The book will frustrate readers seeking a single career checklist with guaranteed dates. That is intentional. Naval offers principles that transfer across eras of technology. Code and media are today’s vivid examples of permissionless leverage; the deeper pattern is finding ways for judgment to scale without linearly scaling hours, while keeping the mind free enough to enjoy the result and kind enough not to destroy the relationships that make compounding possible.</p>
<p>Leave with two scoreboards. External: skills, assets, leverage, trusted relationships. Internal: peace, health, presence, desire under conscious control. Optimize both, or the win feels empty. Reread the Almanack in seasons — one month on specific knowledge, one on leverage, one on meditation — because compressed wisdom reveals more as your context changes and your ego finds new ways to chase status.</p>
<p>Above all, remember that freedom is the point. Money is a tool; status is a game you can win and still lose your life to; peace is a skill; specific knowledge is a path. Build a life where your work can scale and your mind can rest — then give compounding the years it demands without constantly interrupting it for applause.</p>
<p>If your wealth work destroys sleep and relationships, you are funding a future you may not enjoy. If your peace practice becomes avoidance of building, you are calming yourself into stagnation. Weekly, score both dashboards honestly and adjust the next week’s bets.</p>
<p><strong>Lesson:</strong> Build leveraged creative work and a peaceful mind together — freedom needs both a balance sheet and inner quiet.</p>',
  duration_minutes = 27,
  cover_image_url = 'https://covers.openlibrary.org/b/id/10449931-L.jpg',
  short_description = 'Eric Jorgenson’s curated guide to Naval Ravikant’s thinking on wealth, specific knowledge, leverage, judgment, and happiness.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'The Almanack of Naval Ravikant';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'The Almanack of Naval Ravikant');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('How does Naval distinguish wealth from status?', 'They are identical', 'Wealth is assets that earn while you sleep; status is zero-sum social rank', 'Status creates all wealth', 'Wealth is only cash in a wallet', 'B', 1),
  ('What is specific knowledge?', 'Whatever a standard school course teaches everyone', 'Unique, hard-to-train knowledge that feels like play to you', 'Memorizing trivia', 'Only credentials from elite schools', 'B', 2),
  ('Which leverage forms does Naval call more permissionless?', 'Only government jobs', 'Code and media', 'Only physical labor', 'Only inheritance', 'B', 3),
  ('Why is judgment so important in Naval’s framework?', 'Judgment never matters', 'Leverage amplifies decisions, so clear thinking becomes extremely valuable', 'Judgment replaces all skill', 'Only short-term thinking counts', 'B', 4),
  ('How does Naval frame happiness?', 'Only as buying more things', 'As a skill related to peace, presence, and managing desire — aided by meditation', 'As ignoring health', 'As winning status fights', 'B', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'The Almanack of Naval Ravikant';
