UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Domestication shapes your inner agreements</h2>
<ul><li>Childhood rewards and punishments teach you who to be, often through fear, and those unconscious agreements keep running as adult self-judgment.</li></ul>
<h2>2. Be impeccable with your word</h2>
<ul><li>Speak with integrity toward others and yourself; gossip and harsh self-talk poison relationships and identity.</li></ul>
<h2>3. Don’t take anything personally</h2>
<ul><li>Other people’s actions reflect their own story more than your worth; personalizing everything creates needless suffering.</li></ul>
<h2>4. Don’t make assumptions</h2>
<ul><li>Ask questions, clarify meaning, and say what you need instead of inventing stories that breed conflict.</li></ul>
<h2>5. Always do your best</h2>
<ul><li>Your best changes with energy and circumstance; sincere effort ends self-punishment and keeps growth alive.</li></ul>
<h2>6. Freedom comes from new agreements</h2>
<ul><li>You can notice old fear-based contracts and replace them with clearer, kinder practices day by day.</li></ul>

<h1>PART 2 — THE FOUR AGREEMENTS</h1>
<h2>A 24-Minute Read Summary</h2>

<h3>Chapter 1: The Dream of Domestication</h3>
<p>Don Miguel Ruiz opens with a simple but unsettling idea: much of what you call “reality” is a dream built from agreements you never consciously chose. As a child, you learned language, rules, and belonging through a process he calls domestication. Smile and you are praised. Break a rule and you are punished or shamed. Over time, you absorb a picture of what is “good” and “bad,” who you should be, and what will keep you safe. Those lessons do not stay outside you. They become an inner judge that keeps grading your every move.</p>
<p>Domestication is not only about manners or school. It teaches you to fear rejection, to chase approval, and to police yourself so others will not have to. The agreements can look practical on the surface—“work hard,” “be polite,” “don’t fail”—yet many of them run on fear. Fear of not being enough. Fear of being seen. Fear of losing love. Ruiz’s point is not that learning is wrong. It is that unconscious fear-based agreements create a life of constant inner conflict, where you punish yourself for failing standards you may not even believe in.</p>
<p>Once you see domestication as a set of agreements rather than absolute truth, freedom becomes possible. You cannot rewrite childhood overnight, but you can notice which rules still run your reactions. When you snap at yourself after a mistake, ask: whose voice is that? When you hide an opinion to stay liked, ask: what am I afraid will happen? Awareness is the first crack in the old dream. The Four Agreements are offered as a cleaner code—simple enough to remember, strong enough to interrupt the cycle of self-judgment and emotional poison.</p>
<p>Think of domestication as software installed without your consent. Some modules are useful: look both ways, say thank you, finish what you start. Others are malware disguised as virtue: never ask for help, never show anger, never risk looking foolish, always put others first until you disappear. Ruiz invites you to become a conscious programmer of your own agreements. That begins with inventory. List ten rules you live by. Mark which ones still serve love and clarity, and which ones mainly serve fear of punishment or exile. The marked fear rules are candidates for replacement. You do not need a dramatic ceremony. You need honest labeling. Once a rule is labeled as optional rather than sacred, you can test a new behavior in a low-stakes setting and watch what actually happens versus what the old fear predicted.</p>
<p><strong>Lesson:</strong> Much of your suffering comes from unconscious childhood agreements; freedom begins when you notice them as agreements, not final truth.</p>

<h3>Chapter 2: Be Impeccable with Your Word</h3>
<p>The first agreement is the foundation: be impeccable with your word. Impeccable, for Ruiz, means without sin against yourself—using language in a way that does not self-betray. Your word is creative force. What you say shapes what you believe, how others experience you, and the emotional weather of a room. When you speak with integrity—saying what you mean, meaning what you say, and refusing to use words as weapons—you build trust. When you use words carelessly, you scatter your power and damage relationships, including the relationship with yourself.</p>
<p>Impeccability is not the same as blunt cruelty dressed up as honesty. Truth without care can still be a form of attack. The practice asks for clean speech: no unnecessary harm, no manipulation, no promising what you will not do. It also asks for alignment. If you say you will call, call. If you disagree, disagree without character assassination. If you are unsure, say you are unsure instead of inventing certainty. Small acts of verbal integrity compound into a reputation—and a self-image—of reliability.</p>
<p>In daily life, try a short pause before speaking under stress. Ask whether the next sentence builds or poisons. Replace sarcasm that hides resentment with a clearer request. Replace exaggerated self-put-downs with accurate description: “I missed the deadline” instead of “I’m useless.” The first agreement is not about perfect eloquence. It is about refusing to use language as a tool of fear, control, or self-destruction.</p>
<p>Impeccability also covers written communication. Texts sent in anger, vague commitments in email, and public pile-ons are modern forms of careless word use. Before sending a charged message, wait long enough to reread it as if you were the recipient. Ask whether it is true, necessary, and free of hidden punishment. If you need to set a boundary, do so cleanly: name the behavior, name the need, name the next step. Clean does not mean soft. You can be firm and impeccable at once. What you refuse is the extra poison—character attacks, sarcasm that deniable-hurts, and stories presented as facts.</p>
<p>Another practice is repairing broken words quickly. If you said you would do something and failed, acknowledge it without theatrical self-hate. A short repair restores integrity better than a long excuse. Over months, people learn that your yes means yes. That reliability is a form of love in action, and it reduces the drama that unclear speech creates.</p>
<p><strong>Lesson:</strong> Treat your word as creative power—speak with integrity, avoid weaponized language, and refuse to turn speech against yourself.</p>

<h3>Chapter 3: Gossip, Spells, and Self-Talk</h3>
<p>Ruiz treats gossip as a special misuse of the word. Gossip often feels bonding—shared judgment can create temporary closeness—but it spreads emotional poison. When you rehearse someone’s flaws behind their back, you train your mind to look for fault, and you teach listeners that loyalty is conditional. Even “harmless” gossip keeps you inside a dream of comparison and superiority. The alternative is not fake positivity. It is declining to participate in conversations that exist mainly to tear someone down.</p>
<p>More important than gossip about others is gossip about yourself. Many people speak to themselves in ways they would never speak to a friend. “You’re such an idiot.” “Of course you failed.” “Nobody wants you.” Ruiz frames these inner statements as spells: repeated words that cast a reality you then live inside. If you tell yourself you are unworthy often enough, you will act in ways that confirm the story—avoiding chances, accepting poor treatment, or sabotaging success.</p>
<p>Breaking the spell starts with catching the phrase. Write down the three insults you use on yourself most often. For each one, draft a replacement that is truthful without being cruel. “I am learning this skill” instead of “I’m talentless.” “I was tired and short-tempered” instead of “I’m a terrible person.” Then practice outward restraint: when a conversation turns into pile-on gossip, change the subject, leave, or say something fair. Cleaning your word in public and in private is the same muscle.</p>
<p>In workplaces, gossip often masquerades as “alignment” or “venting.” Venting can be healthy when it aims at processing emotion with a trusted person and then returning to action. Gossip aims at bonding through someone’s absence and usually leaves a residue of contempt. A useful test: would you say the same words if the person walked in? If not, you are likely casting a spell you do not want to own. Choose a confidant carefully, focus on your feelings and requests, and avoid rehearsing a villain narrative that becomes harder to reverse later.</p>
<p>For self-talk, try a third-person correction when emotions run high: “Alex is stressed and made a mistake; Alex can fix the next step.” This small distance can interrupt identity fusion with failure. Combine it with body basics—water, walk, sleep—because exhausted minds gossip against themselves more viciously. Impeccability is easier when your nervous system is not on fire.</p>
<p><strong>Lesson:</strong> Gossip and harsh self-talk are misuse of the word; stop casting spells that make misery feel like destiny.</p>

<h3>Chapter 4: Don’t Take Anything Personally</h3>
<p>The second agreement sounds simple and feels almost impossible at first: don’t take anything personally. Ruiz’s claim is that what people say and do is a projection of their own dream—their fears, beliefs, wounds, and mood. If someone insults you, the insult reveals their map of the world more than it measures your value. If someone praises you excessively, that too can be about their need, not a permanent verdict on your worth. Taking everything personally makes you a victim of every opinion that floats past.</p>
<p>This does not mean you become numb or refuse all feedback. Useful information can arrive in clumsy packaging. The agreement asks you to separate data from identity. “The report had errors” can be useful. “You are worthless” is someone else’s poison. Even kind feedback is not a crown you must wear forever. When you stop personalizing, you gain choice: listen, clarify, set a boundary, or walk away—without collapsing into shame or exploding into defense.</p>
<p>Practice in small doses. The next time a sharp comment lands, pause and name the alternative story: “This may be about their stress, not my essence.” Check the facts that matter. If a pattern of disrespect continues, protect yourself without needing to convert the other person. Emotional independence is not coldness. It is refusing to let every passerby edit your self-worth.</p>
<p>Not taking things personally is especially hard with people you love, because their opinions matter and their moods affect shared life. The agreement does not ask you to stop caring. It asks you to stop confusing impact with identity verdict. Your partner’s irritation may be about sleep, money fear, or their own unfinished day. You can still apologize for your part without agreeing that you are fundamentally defective. Likewise, you can refuse to accept cruel labels even from someone important. Love and self-respect can coexist.</p>
<p>Online life weaponizes personalization. Comments are designed to hook identity. Practice a delay rule: do not reply to charged messages for a set time. Ask what part is useful data and what part is someone discharging stress into a text box. Unsubscribe from arenas that constantly bait your worth. Immunity includes choosing fewer poison sources.</p>
<p><strong>Lesson:</strong> Other people’s actions are about their own dream; take useful information, but do not let opinions define your worth.</p>

<h3>Chapter 5: Immunity to Emotional Poison</h3>
<p>When you take things personally, you absorb emotional poison—anger, envy, blame, and fear that were never yours to carry. Ruiz describes a kind of immunity that grows from the second agreement. You can still feel hurt; feeling is human. The difference is that hurt no longer automatically becomes a story of global rejection. You notice the sting, breathe, and return to your own center instead of launching a counterattack or a weeks-long rumination loop.</p>
<p>Personalizing also fuels the need to control how others see you. You manage every expression, over-explain, or people-please so nobody can form a negative picture. That strategy is exhausting and never finished, because you cannot manage everyone’s inner world. The second agreement frees energy for your own integrity. You become less reactive in traffic, less devastated by social media comments, less derailed by a cold email. Life still contains conflict. You simply stop volunteering as the storage unit for everyone else’s mood.</p>
<p>A practical drill: after a charged interaction, write two columns. Column one: what actually happened in observable terms. Column two: the story you invented about what it means for your identity. Seeing the gap weakens the spell. Over time, you will still care about people—you will just care without confusing their weather for your climate.</p>
<p>Building immunity also means reducing the secondary suffering of rumination. After a slight, the first hit is often small; the second hit is the story you replay for days. Set a container: ten minutes to feel and journal, then a deliberate return to a chosen task. If the issue needs a conversation, schedule it. If it does not, close the loop. This is not repression. It is refusing to rent your attention to a moment that already ended. Pair the practice with the first agreement: do not speak poison about the person all week as a substitute for resolution.</p>
<p><strong>Lesson:</strong> Emotional immunity means feeling the sting without storing other people’s poison as proof of who you are.</p>

<h3>Chapter 6: Don’t Make Assumptions</h3>
<p>The third agreement targets a habit that quietly destroys relationships: making assumptions. You assume you know what someone meant. You assume they know what you need. You assume silence equals rejection, busyness equals indifference, or a delayed reply equals disrespect. Then you react to the story rather than reality. Arguments often begin not with facts but with two unspoken novels colliding.</p>
<p>Assumptions feel efficient because asking questions can feel vulnerable. Clarifying might reveal that you were wrong, or that you must state a need out loud. Many people would rather suffer in a private fantasy than risk an awkward conversation. Ruiz insists the opposite path is freedom: ask. “What did you mean by that?” “When you said you were fine, was that complete?” “I need help on Thursday—can you do that?” Clear questions replace mind-reading with shared reality.</p>
<p>Assumptions also appear in self-judgment. You assume one failure predicts permanent failure. You assume others are judging you as harshly as you judge yourself. Challenge those leaps. Gather evidence. Speak the unclear thing before it hardens into resentment. The courage to clarify is often less painful than months of silent storytelling.</p>
<p>Assumptions flourish under fatigue and ambiguity. When information is missing, the brain fills gaps with familiar fears. That is why delayed replies become rejection stories and neutral faces become disapproval stories. Counter with a default curiosity script: “I don’t know yet—I can ask.” Keep a short list of high-cost assumptions you make repeatedly in your closest relationship and convert each into a standing question you are willing to ask even when awkward. Awkward clarity is cheaper than elegant misunderstanding.</p>
<p>At work, assumptions about priorities create thrash. Confirm success criteria in writing. Repeat deadlines aloud. Ask “What does done look like?” These questions are not signs of incompetence; they are signs of professionalism. Teams that normalize clarification make fewer enemies out of silence.</p>
<p><strong>Lesson:</strong> Replace mind-reading with questions and clear requests; assumptions turn imagination into unnecessary conflict.</p>

<h3>Chapter 7: Clarity as an Act of Love</h3>
<p>Not making assumptions is not only a conflict-avoidance tactic. It is a way of loving truth more than comforting stories. In close relationships, unspoken expectations are especially dangerous. You may assume your partner “should know” how you like support, or that a colleague “should know” a deadline matters. When they fail the invisible test, you punish them for a rule they never agreed to. That is unfair to them and exhausting for you.</p>
<p>Clarity requires courage and specificity. Instead of “You never care,” try “When plans change without a message, I feel anxious—can we agree to text if we’ll be late?” Instead of assuming a friend’s distance means the friendship is over, ask how they are doing and what they need. Instead of assuming your team understands priorities, write them down. Specificity reduces drama because it gives people something real to respond to.</p>
<p>Also clarify with yourself. Many assumptions begin as unclear desires. If you do not know what you want, you will expect others to guess and then resent them for guessing wrong. Spend a few minutes naming your actual request before a hard conversation. The third agreement becomes a daily habit of curiosity: prefer questions over conclusions until you have checked.</p>
<p>Clarity includes saying no without a fictional yes. Many conflicts begin because someone assumed agreement from a polite non-answer. Practice explicit commitments: yes, no, or a timed maybe with a date you will decide. If you need time, say so. If you cannot meet a need, offer what you can without promising what you cannot. This kind of clarity can disappoint in the short term and build trust in the long term, because people stop having to guess your real capacity.</p>
<p>Also clarify positive desires, not only problems. Tell people what you enjoy, how you like to receive support, and what good looks like. Positive clarity prevents partners and colleagues from playing a perpetual penalty shootout against invisible standards. The third agreement, lived well, makes love and collaboration less like telepathy exams.</p>
<p><strong>Lesson:</strong> Clarity is kindness—state needs and meanings explicitly so people are not punished for failing invisible tests.</p>

<h3>Chapter 8: Always Do Your Best</h3>
<p>The fourth agreement holds the others together: always do your best. Without it, the first three can become new weapons of perfectionism. You might demand flawless speech, perfect non-reactivity, and constant clarity, then hate yourself when you fall short. Ruiz’s correction is compassionate and practical. Your best is not a fixed output. It changes with health, sleep, grief, weather, and season of life. Some days your best is excellent work. Some days your best is getting through with basic decency.</p>
<p>Doing your best means showing up with sincerity rather than half-effort followed by self-punishment. When you know you truly did what you could, regret has less fuel. You may still review mistakes and improve, but you stop the courtroom drama of endless self-prosecution. Conversely, when you withhold effort and then invent excuses, you create a different poison: the quiet shame of knowing you abandoned yourself.</p>
<p>Apply this agreement by defining “best” as honest engagement, not comparison with your highlight reel or someone else’s pace. After a hard day, ask: given my real conditions, did I act with integrity? If yes, rest without a lecture. If no, adjust tomorrow without identity collapse. The fourth agreement turns growth into a sustainable practice instead of a moral panic.</p>
<p>Doing your best includes preparation and recovery, not only the performance moment. If you repeatedly underprepare and then call it “my best under stress,” you are gaming the agreement. Sincere best means giving the effort the situation reasonably deserves, then releasing the rest. It also means stopping when more grinding would only produce self-cruelty without better outcomes. Wisdom is part of best, not a loophole.</p>
<p>Measure best by process metrics you control: Did I tell the truth? Did I ask instead of assume? Did I take a breath before reacting? Did I keep the commitment I made? Outcome metrics matter in life, but they are incomplete moral scores. Separating process integrity from outcome luck keeps the fourth agreement sane.</p>
<p><strong>Lesson:</strong> Do your sincere best under today’s conditions; that ends both laziness-shame and perfectionist self-attack.</p>

<h3>Chapter 9: Best as a Moving Target</h3>
<p>People often resist the fourth agreement because they hear “do your best” as “do more until you break.” Ruiz means the opposite of burnout culture. If you are ill, your best may be rest and fewer commitments. If you are learning, your best includes awkward attempts. If you are grieving, your best may be kindness in a smaller radius. Honoring a moving target prevents the false belief that worth equals maximum output every day.</p>
<p>This flexibility also protects the other agreements. On a depleted day, impeccability might mean fewer words, not perfect speeches. Not taking things personally might mean delaying a reply until you are calm. Not making assumptions might mean writing a clarifying message instead of forcing a late-night confrontation. Best effort includes choosing the form of integrity that fits your capacity.</p>
<p>A useful ritual is a two-minute evening review. Name one moment you honored an agreement and one moment you slipped. For the slip, choose one repair: an apology, a clearer ask, or a gentler self-statement. Keep the review factual. The goal is learning, not a new domestication system where the inner judge grades your spiritual progress. Doing your best includes how you treat yourself after you fail.</p>
<p>Share the moving-target idea with people who depend on you. If your capacity drops because of illness or overload, communicate the new best rather than silently failing old standards. “This week I can deliver the draft, not the polish” is impeccable and assumption-reducing at once. People can work with reality. They struggle with surprise disappointment born from unspoken capacity changes. The fourth agreement becomes relational when you narrate your real bandwidth without shame theater.</p>
<p>Beware comparing your exhausted best to someone else’s highlight best. Comparison reinstalls domestication through social media. Do your work, honor your season, and let other people’s scoreboards belong to them. That is another way of not taking things personally—including not taking other people’s success as your indictment.</p>
<p><strong>Lesson:</strong> Let “best” flex with real life so the agreements stay humane practices, not a new perfectionist religion.</p>

<h3>Chapter 10: Breaking Old Agreements</h3>
<p>Ruiz does not pretend that reading four rules rewires decades of training. Old agreements feel like reality because they are rehearsed. Breaking them requires attention, repetition, and patience. You will take something personally and notice five minutes later. That noticing is success. You will gossip, catch yourself, and stop mid-sentence. That interruption is freedom practicing in public. Transformation is less like a switch and more like recovering from a long habit of self-domestication.</p>
<p>One practical method is to identify a single recurring agreement that hurts you—“I must never disappoint anyone,” “If they are upset, I caused it,” “Asking for help is weakness.” Write the old agreement and a replacement. “I can disappoint someone and still be a good person.” “Their mood is not automatically my crime.” “Asking is how adults solve problems.” Then look for daily chances to act from the new line, especially in small stakes situations where fear is quieter.</p>
<p>Expect resistance. The old dream argues back: you will be selfish, unsafe, or naive. Test reality carefully. Boundaries can be firm and kind. Clarity can be warm. Not taking things personally does not require staying in harm. The Four Agreements are not a command to tolerate abuse. They are tools for ending self-abuse and ending the habit of turning every interaction into a referendum on your soul.</p>
<p>Breaking agreements can feel like betrayal of your tribe. If your family system rewards self-erasure, choosing clarity may trigger pushback. Expect it without treating pushback as proof you are wrong. Stay kind, stay boundaried, and keep your new agreement small enough to sustain. Dramatic overnight personality overhauls often rebound. Quiet consistency rewrites identity more reliably. Track evidence weekly: moments you paused before gossip, questions you asked instead of assuming, insults you did not personalize, efforts you respected without perfection.</p>
<p><strong>Lesson:</strong> Replace one painful old agreement at a time through noticing, rewriting, and small repeated actions.</p>

<h3>Chapter 11: Living the Four Together</h3>
<p>The agreements reinforce each other. When you are impeccable with your word, you create less confusion, so others have fewer reasons to invent stories—and you have fewer reasons to invent theirs. When you refuse to take things personally, you can hear feedback without collapsing, which makes honest conversation safer. When you stop assuming, your words become questions and clean statements instead of accusations. When you do your best, you keep practicing even after imperfect days.</p>
<p>In conflict, try a simple sequence. Pause before speaking (impeccability). Remind yourself the other person’s intensity may be their dream (not personal). Ask what they mean and state what you mean (no assumptions). Choose the best response available given your energy (do your best). This sequence will not win every argument. It will prevent many unnecessary ones and shorten the ones that are necessary.</p>
<p>At work, the four agreements improve culture without requiring everyone to share your philosophy. Clean commitments, less gossip, curiosity instead of mind-reading, and sincere effort are universally useful. At home, they reduce the quiet wars of unspoken expectation. With yourself, they soften the inner judge that domestication installed. The point is not to become spiritually impressive. The point is to suffer less while staying engaged with life.</p>
<p>When the agreements conflict in a moment—truth versus kindness, clarity versus timing—use “do your best” as the tiebreaker and choose the least poisonous option available now. Sometimes impeccability means waiting an hour so your words will be clean. Sometimes it means speaking immediately before an assumption hardens in a group. There is no rigid algorithm. There is a compass: reduce fear-based harm, increase truth with care, keep your side of the street clean.</p>
<p><strong>Lesson:</strong> Use the four agreements as a linked practice—clean speech, emotional independence, clarity, and sincere effort reinforce one another.</p>

<h3>Chapter 12: A Daily Practice of Freedom</h3>
<p>Freedom, in Ruiz’s sense, is living without the heavy fog of fear-based self-judgment. It is not a permanent bliss state. It is a lighter way of meeting ordinary days. You still have responsibilities, preferences, and edges. You simply stop agreeing to interpret every mistake as proof that you are unworthy, every silence as abandonment, and every conflict as a chance to poison with words.</p>
<p>Build a small daily practice. Morning: choose one agreement as today’s focus. Midday: one breath before a difficult message. Evening: one honest review without cruelty. Weekly: one courageous clarification you have been avoiding. These habits are modest on purpose. Domestication was built through repetition; liberation is built the same way. You are not trying to become a different species. You are trying to become less ruled by fear’s old contracts.</p>
<p>If you remember nothing else, remember this: your word can heal or harm, including when spoken silently to yourself; other people’s behavior is not a final scoreboard of your value; assumptions are stories that need checking; and sincere best effort is enough for today. Practice those four lines until they feel more natural than the old dream. That is the quiet revolution Ruiz offers—not escape from the world, but a freer way to live inside it.</p>
<p>As a closing practice, pick a daily anchor tied to an existing habit. With morning coffee, recite the four agreements in plain words. With your phone’s lock screen, keep a one-line reminder: “Word. Not personal. Ask. Best.” With each evening walk, choose tomorrow’s focus agreement. Anchors beat willpower. They make freedom habitual. If you miss a day, resume without a trial. The old domestication used punishment to train you. The new training uses return.</p>
<p>Over a year, the cumulative effect is a quieter mind and cleaner relationships. You will still be human. You will still misunderstand and repair. The difference is that repair becomes normal, and self-rejection becomes optional. That optionality is the freedom Ruiz points toward—available in ordinary kitchens, inboxes, and conversations, one agreement at a time.</p>
<p><strong>Lesson:</strong> Freedom grows from daily, imperfect practice of the four agreements until they outweigh the old fear-based dream.</p>',
  duration_minutes = 24,
  cover_image_url = 'https://covers.openlibrary.org/b/isbn/9781878424310-L.jpg',
  short_description = 'Don Miguel Ruiz’s Toltec-inspired code: be impeccable with your word, don’t take anything personally, don’t make assumptions, and always do your best.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'The Four Agreements';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'The Four Agreements');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('What is the first agreement?', 'Always be right', 'Be impeccable with your word', 'Never speak', 'Win every argument', 'B', 1),
  ('What does ''don’t take anything personally'' mean?', 'Ignore all feedback forever', 'Others’ actions reflect them more than your worth', 'Never set boundaries', 'Agree with every insult', 'B', 2),
  ('How does Ruiz suggest you avoid assumptions?', 'Mind-read better', 'Ask questions and communicate clearly', 'Assume the worst always', 'Stay silent for years', 'B', 3),
  ('What is true of ''always do your best''?', 'Your best is identical every day', 'Your best changes with circumstances; sincerity matters', 'Only perfection counts', 'Best means outworking everyone', 'B', 4),
  ('In Ruiz’s framing, what does childhood ''domestication'' create?', 'Only practical skills', 'Unconscious fear-based agreements and inner judgment', 'Permanent freedom', 'Guaranteed success', 'B', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'The Four Agreements';
