UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Go small to go big</h2>
<ul><li>Extraordinary results come from narrowing focus, not from doing more.</li></ul>
<h2>2. The Focusing Question</h2>
<ul><li>Ask what ONE action makes everything else easier or unnecessary.</li></ul>
<h2>3. Dominoes and successive success</h2>
<ul><li>Line up priorities so each win unlocks the next larger outcome.</li></ul>
<h2>4. Time blocking your ONE Thing</h2>
<ul><li>Protect a non-negotiable daily block before interruptions win.</li></ul>
<h2>5. Lies that scatter focus</h2>
<ul><li>Multitasking, all-day willpower myths, and balanced-everything thinking dilute results.</li></ul>
<h2>6. Purpose, priority, and productivity</h2>
<ul><li>Connect big purpose to a clear priority, then to protected daily action.</li></ul>
<h2>7. Live with purpose and permission to be extraordinary</h2>
<ul><li>Accept tradeoffs, protect the block, and let successive focus compound.</li></ul>
<h1>PART 2 — THE ONE THING</h1>
<h2>A 25-Minute Read Summary</h2>
<h3>Chapter 1: Extraordinary results require focus</h3>
<p>Gary Keller’s The One Thing (written with Jay Papasan, 2013) argues that success is sequential, not simultaneous. Keller, founder of a giant real-estate franchise network, noticed that breakthrough outcomes came from focusing on the few actions that mattered most — often one action at a time — rather than from heroic multitasking or endless list-clearing. The book’s enemy is scattered effort: long to-do lists that create motion without progress.</p>
<p>Keller’s thesis is simple and uncomfortable. If you chase everything, you achieve diluted versions of everything. If you identify the lead action with cascading payoff and apply disproportionate energy there, other tasks either become easier or fall away as unnecessary. Extraordinary results are not produced by extraordinary busyness; they are produced by extraordinary focus repeated over time.</p>
<p>“Go small” sounds paradoxical in a culture that celebrates bigger goals, bigger teams, and bigger calendars. Keller means go small in focus so you can go big in results. Narrowing is not thinking small; it is aiming precisely. A wide aim wastes force. A narrow aim concentrates force until something important moves.</p>
<p>Most professionals confuse activity with advancement. Emails answered, meetings attended, and tasks checked can feel like a productive day while the year’s most important outcome barely moves. The One Thing asks you to invert that pattern: make the important thing non-negotiable and let lesser things negotiate for leftover scraps of time.</p>
<p>Audit your calendar for the past week. How many hours went to your most important outcome versus reactive noise? That ratio is your real strategy, regardless of what you say your priorities are. If the ratio shocks you, the book has already started working.</p>
<p>Keller’s background in building a large real-estate organization gives the book an operator’s bias: theory must survive contact with calendars, commissions, and human distraction. He saw talented people stall not from lack of intelligence but from fragmented priorities. The One Thing is his attempt to name the pattern behind people who break through — they sequence success instead of spraying effort.</p>
<p>Notice how often “priorities” in modern speech means a long list. Historically, priority was singular. Recovering that singularity is the emotional and strategic heart of the book. You are allowed — required — to have a lead aim for this season, even if other aims remain alive in maintenance mode.</p>
<p><strong>Lesson:</strong> Extraordinary results come from narrowed focus on the highest-leverage action — not from doing more things.</p>
<h3>Chapter 2: The Focusing Question</h3>
<p>Keller’s central tool is the Focusing Question: “What’s the ONE Thing I can do such that by doing it everything else becomes easier or unnecessary?” The question forces leverage thinking. It is not “What can I do?” (infinite) or “What should I do someday?” (vague). It is the single action with cascading payoff — the move that rearranges the rest of the board.</p>
<p>You can ask it at different altitudes. Big-picture: What is the ONE Thing I can do for my life, career, health, or relationships? Small-picture: What is the ONE Thing for this year, this month, this week, today? The answers should nest. Today’s ONE Thing serves the week’s; the week’s serves the year’s; the year’s serves a larger purpose. When the nest breaks, days become random and years become surprising for the wrong reasons.</p>
<p>The question also trains discrimination. Many tasks are good. Fewer are great. Almost none are the ONE Thing. Keller wants you to become restless with mere goodness when greatness is available through focus. That restlessness is productive when it leads to elimination, not when it leads to anxiety and more lists.</p>
<p>People often resist the question because it feels risky to choose. Choosing one thing means not choosing others — for now. But refusing to choose is still a choice: you choose dilution. The Focusing Question makes the tradeoff conscious so you can defend it.</p>
<p>Write the question at the top of your daily note. Answer it before you open inbox or chat. If you cannot name the ONE Thing in one sentence, you are not ready to be busy yet — you are still clarifying.</p>
<p>The question’s power is in its constraints. “ONE Thing” forces singularity. “I can do” forces agency rather than wishful thinking. “Such that by doing it everything else becomes easier or unnecessary” forces leverage rather than mere urgency. Urgency screams; leverage rearranges. Most to-do lists are urgency machines. The Focusing Question is a leverage machine.</p>
<p>When answers feel fuzzy, shrink the time horizon. If you cannot name the year’s ONE Thing, name the week’s. If the week is unclear, name today’s. Clarity often arrives from the bottom up once action begins, then informs the higher altitudes on the next planning pass.</p>
<p><strong>Lesson:</strong> Use the Focusing Question to find the single action that makes everything else easier or unnecessary.</p>
<h3>Chapter 3: Dominoes — successive success</h3>
<p>Keller uses the domino metaphor to explain how focus creates outsized outcomes. Line up priorities so each success knocks over the next. Geometrically, successive dominoes can topple larger and larger pieces if sequenced well. In life and work, early focused wins create capacity, credibility, skills, and options that unlock later wins that would have been impossible at the start.</p>
<p>The mistake is trying to knock over every domino at once — starting twelve initiatives, splitting attention, and watching none fall cleanly. Another mistake is knocking over random small dominoes that do not touch the line that leads to your goal. Activity can be high while the chain toward the extraordinary outcome never forms.</p>
<p>Successive success also reframes patience. You do not need the final result on day one; you need the correct next domino. Careers, businesses, health transformations, and creative bodies of work usually look like sequences of focused periods, not like simultaneous mastery of everything. Keller’s model legitimizes doing less now in service of more later.</p>
<p>Map your goal backward. What must be true one year from now? What must be true ninety days from now for that year to be realistic? What must be true this week? What is today’s lead domino? If today’s action does not touch the chain, it may be maintenance or distraction dressed as work.</p>
<p>Revisit the line monthly. Domino sequences change as reality teaches you. The discipline is not rigidity about a plan; it is rigidity about having a lead priority and protecting it until the next one becomes obvious.</p>
<p>Think of skill, reputation, capital, and relationships as domino sizes. Early focused practice builds skill (small domino). Skill produces visible results (larger). Results attract trust and resources (larger still). Trying to attract resources before skill is trying to topple a huge domino with no run-up. Keller’s sequence protects you from that fantasy.</p>
<p>Teams can misuse the metaphor by declaring twelve “lead dominoes.” A lead domino is singular by definition. Supporting tasks exist, but they are not co-equal leads. If everything is a lead domino, you are back to a list with better branding.</p>
<p><strong>Lesson:</strong> Line up priorities as successive dominoes — each focused win should unlock a larger next outcome.</p>
<h3>Chapter 4: The lies that keep you scattered</h3>
<p>Keller attacks several cultural lies that destroy focus. One is that everything matters equally. When everything is important, nothing is. Priority becomes a plural word and loses force. Another lie is that multitasking is a strength. In cognitively demanding work, switching costs fragment attention, increase errors, and create the illusion of progress while deep work starves.</p>
<p>A related lie is that a balanced life means equal attention to every area every day. Keller argues for counterbalancing over time rather than forced daily equality. Some seasons require disproportionate investment in a career launch, a health reset, or a family crisis. Trying to keep every plate spinning identically every day can prevent breakthrough in any domain.</p>
<p>Another lie is that willpower is always on tap. Keller emphasizes that willpower is finite and depletes with decisions, stress, and temptation. If you schedule your most important work for the end of a depleted day, you are stacking the deck against yourself. Focus is not only a values problem; it is an energy-timing problem.</p>
<p>Busyness as a badge is perhaps the most social of the lies. Being overwhelmed can signal importance in some cultures. Keller wants results, not theater. A calm calendar with a protected block for the ONE Thing can outperform a chaotic calendar full of reactive heroics.</p>
<p>Name the lie that catches you most often — multitasking pride, balance perfectionism, late-day heroics, or busy status. Design one rule that breaks it this week, such as no chat during the first work block.</p>
<p>Keller also challenges the idea that you should wait to feel ready or perfectly balanced before focusing. Readiness often follows commitment, not the reverse. Balance, when forced daily across every role, can become a sophisticated avoidance of the discomfort of choosing. Seasons of imbalance toward a worthy ONE Thing can be healthier than chronic mediocrity everywhere.</p>
<p>Watch your language for lie-markers: “I don’t have time,” when you mean “I didn’t prioritize”; “I’m great at multitasking,” when you mean “I’m afraid to miss anything”; “I’ll start when things calm down,” when calm never arrives. Language reveals the story that keeps you scattered.</p>
<p><strong>Lesson:</strong> Reject the lies of equal urgency, multitasking, all-day willpower, and busy-as-badge thinking that scatter results.</p>
<h3>Chapter 5: Purpose, priority, and productivity</h3>
<p>Keller connects three P’s: purpose, priority, and productivity. Purpose answers why your effort matters — the larger aim that makes sacrifice intelligible. Priority answers what matters most now — the ONE Thing nested under purpose. Productivity is the protected action that moves the priority. Without purpose, priority feels arbitrary. Without priority, productivity becomes efficient wandering. Without productivity, purpose and priority remain posters on a wall.</p>
<p>People often jump straight to productivity hacks — apps, morning routines, inbox tricks — without clarifying purpose and priority. Hacks then accelerate the wrong work. The One Thing insists on order: know the destination well enough to choose a lead action, then defend time for that action as if results depended on it — because they do.</p>
<p>Purpose need not be grandiose to be useful. It can be as concrete as building a craft, providing for a family with integrity, recovering health, or creating work that helps a specific group. What matters is that it is clear enough to generate a priority when options proliferate. Vague purpose produces vague days.</p>
<p>Priority is where courage shows up. Saying yes to the ONE Thing means saying not now to attractive alternatives. Keller’s framework makes that courage habitual by turning it into a daily question rather than a rare crisis decision.</p>
<p>Write one paragraph of purpose, one sentence of current priority, and one calendar block for productivity. If any layer is missing, fix that layer before optimizing tools. Tools cannot save an unclear aim.</p>
<p>Purpose without priority becomes inspirational fog. Priority without purpose becomes grind that collapses under stress. Productivity without either becomes inbox theater. Keller’s chain is a diagnostic: if you feel busy and empty, check purpose; if you feel inspired and stuck, check priority; if you know the priority and still stall, check the calendar block.</p>
<p>Revisit purpose quarterly in writing — one page maximum. Long manifesto documents tend to be unread. A short purpose statement that can generate a Focusing Question answer is more useful than a beautiful unused essay.</p>
<p><strong>Lesson:</strong> Connect purpose to a clear priority, then to protected daily productivity — hacks fail without that chain.</p>
<h3>Chapter 6: Time blocking your ONE Thing</h3>
<p>Time blocking is Keller’s practical fortress for focus. You schedule a non-negotiable block for your ONE Thing the way you would schedule a critical meeting with someone you respect — because you are meeting the future version of your results. If the block is optional, interruptions will win. The world is designed to fragment you; the block is designed to refuse fragmentation.</p>
<p>Keller recommends doing the ONE Thing early, when willpower and energy are freshest. Morning blocks are not morally superior; they are strategically safer for many people because the day’s chaos has not yet arrived. If your best energy is later, block that instead — but block something real, not leftover scraps after inbox victory.</p>
<p>Protecting the block requires social courage. You may need to decline meetings, delay replies, close the door, silence notifications, or explain to collaborators that deep work time is how you create the value they want from you. Without boundaries, the Focusing Question becomes a journaling exercise with no calendar consequences.</p>
<p>Time blocking also applies to planning and to personal life. Keller suggests blocking time to think about priorities, and blocking time for the ONE Things in health and relationships, not only career. Otherwise work focus can succeed while life collapses around it — a hollow form of productivity.</p>
<p>Put a recurring block on the calendar for the next thirty days. Treat misses as serious. If something must override it, reschedule the block like a missed flight, not like a forgotten nice-to-have.</p>
<p>Make the block visible to collaborators. Mystery bans create conflict; clear norms reduce it. “I’m in a maker block until 11; emergencies only” is kinder than silent unavailability followed by resentment. Keller’s method scales better when the social system around you understands the rule.</p>
<p>If your job truly forbids long blocks, claim the largest contiguous fragment you can and defend it fiercely — even forty-five focused minutes daily beats eight interrupted hours of fake progress. Negotiate toward larger blocks as you prove the value of the output those blocks create.</p>
<p><strong>Lesson:</strong> Time-block your ONE Thing as non-negotiable — usually when energy is freshest — before the world interrupts.</p>
<h3>Chapter 7: Willpower and the cost of late focus</h3>
<p>Keller’s willpower discussion supports the timing of the ONE Thing. Decision fatigue is real in practice even when debates continue in research: after hours of choices, self-control and sharp focus often feel harder. If your most important cognitive work waits until after a day of meetings, errands, and micro-decisions, you are asking a tired brain for elite performance.</p>
<p>This is why “I’ll do what matters after I clear the decks” so often fails. The decks never stay clear. Reactive work regenerates. Meanwhile the ONE Thing remains postponed until motivation is lowest. Keller’s counsel is to reverse the order: do the ONE Thing first; let decks be cleared afterward with remaining capacity.</p>
<p>Willpower is also shaped by environment. A phone on the desk, an open chat pane, and a snack within reach all tax restraint. Reducing the need for willpower — by removing cues and pre-committing the block — beats relying on heroic self-control. Focus systems beat focus moods.</p>
<p>Sleep, food, and stress modulate the same capacity. Burning the candle to prove dedication can destroy the very resource focus requires. Keller’s model is ambitious without glorifying depletion. Extraordinary results need repeatable energy, not a single all-nighter myth.</p>
<p>For one week, move your hardest creative or strategic task into your first work block. Track quality and completion rate compared with late-day attempts. Let the data argue with your old sequencing habit.</p>
<p>Also notice what you spend willpower on before the ONE Thing. Outfit choices, social feeds, heated email replies, and snack negotiations all draw from the same limited pool for many people. Automating morning routines — clothes, breakfast, first app opened — conserves decision fuel for the work that matters.</p>
<p>If evenings are your only quiet time, protect them as seriously as mornings, and reduce daytime drains that leave you empty. The principle is timing relative to your energy curve, not a moral law that dawn is virtuous.</p>
<p><strong>Lesson:</strong> Do your ONE Thing when willpower is strongest — usually early — instead of after reactive work empties the tank.</p>
<h3>Chapter 8: The four thieves of productivity</h3>
<p>Keller describes “thieves” that steal focus even from people who know their ONE Thing. One thief is inability to say no. Every yes is a trade against the block. Without a graceful no, your calendar fills with other people’s priorities. Another thief is fear of chaos: the belief that if you are not constantly available, things will fall apart. Some chaos is the price of depth; trying to prevent all chaos prevents all extraordinary work.</p>
<p>Poor health habits steal productivity by lowering energy and mood. You cannot sustain focus on willpower alone if sleep and body are neglected. Another thief is an environment that does not support your goals — constant interruptions, the wrong collaborators, or tools that pull you into shallow loops.</p>
<p>These thieves matter because motivation alone cannot outrun a hostile setup. Keller wants readers to design support: scripts for declining, expectations with teams about response times, health basics, and a workspace that makes the ONE Thing easier than distraction.</p>
<p>Identify your primary thief this month. If it is saying no, write three polite decline templates. If it is chaos fear, define what “good enough availability” means and defend deep work outside those windows. If it is health, make sleep the supporting ONE Thing for a season.</p>
<p>Focus is not only an inner virtue. It is a negotiated relationship with your environment and the people in it. Treat that negotiation as part of the work.</p>
<p>A subtler thief is undefined success. If you never define what “done” means for today’s ONE Thing, the block expands into endless polishing or collapses into browsing. Start the block by writing a done-definition in one line. End by checking it. Closure trains the brain that focus episodes finish — which makes starting tomorrow easier.</p>
<p>Another environmental fix: put the phone in another room during the block. Willpower debates lose to distance. Keller’s thieves chapter is ultimately about designing a life where the right behavior is the path of least resistance.</p>
<p><strong>Lesson:</strong> Defend focus from the thieves of weak boundaries, chaos fear, poor health, and unsupportive environments.</p>
<h3>Chapter 9: Living with purpose and accepting tradeoffs</h3>
<p>Extraordinary focus requires accepting that you will disappoint some expectations. Keller’s permission to be extraordinary is permission to be uneven for a while — to invest disproportionately where the lead domino sits. Perfectionist balance can be a socially approved way to avoid commitment.</p>
<p>Living with purpose means letting your big aim inform daily tradeoffs without turning life into grim sacrifice theater. You still need relationships, rest, and health. The point is sequencing and proportion, not martyrdom. Counterbalance over time: after a season of career intensity, a season of family or recovery may become the ONE Thing. The method stays; the content of the ONE Thing evolves.</p>
<p>Guilt is a common companion of focus. When you protect a block, someone may want that hour. Keller’s framework helps you explain the why: this focus is how you create the results that serve the larger purpose, including responsibilities to others. You are not disappearing; you are concentrating.</p>
<p>Review tradeoffs quarterly with honesty. Are you focused or merely avoiding? Are you investing in a real domino chain or hiding inside one comfortable task? Purpose without review can become stubbornness. Review without purpose can become drift.</p>
<p>Write the tradeoffs you are currently accepting and the ones you refuse to accept. Clarity reduces ambient guilt and makes your nos cleaner.</p>
<p>Talk about tradeoffs with the people they affect. Unilateral disappearing creates relationship debt that eventually bankrupts your focus. Shared purpose — “I’m blocking mornings to finish certification so our finances stabilize” — turns a tradeoff into a team strategy. Silence turns it into abandonment narratives.</p>
<p>Permission to be extraordinary is not permission to be careless with health or vows. Keller’s counterbalancing idea exists to prevent that misreading. Go hard on the lead domino; maintain the floors that keep you human.</p>
<p><strong>Lesson:</strong> Accept conscious tradeoffs in service of purpose — extraordinary focus is uneven by design, then rebalanced over time.</p>
<h3>Chapter 10: Building a habit of successive focus</h3>
<p>The One Thing becomes powerful when it leaves the page and becomes a habit loop: ask the Focusing Question, time-block the answer, protect the block, knock over today’s domino, repeat. Over months, successive focused days create outcomes that scattered years never produce. The method is simple; the difficulty is social and emotional, not intellectual.</p>
<p>Start smaller than ego wants. A ninety-minute daily block kept for sixty days beats a fantasized four-hour block abandoned in a week. Successive success applies to the focus habit itself. Make the habit the first domino if your current problem is inconsistency.</p>
<p>Track lead measures, not only lag outcomes. Lag outcomes are revenue, book finished, weight lost. Lead measures are blocks completed, words written, workouts done. Keller’s world rewards people who manage the controllable inputs that cause results.</p>
<p>Expect resistance from your old identity as a busy multitasker. When the urge to “just check” arrives during the block, treat it as a cue to return, not as a verdict that focus is impossible. The muscle grows by reps.</p>
<p>For the next twenty-one workdays, run a single experiment: one Focusing Question answer, one protected block, one end-of-day check — did the domino fall? Do not add new systems until this one is boringly reliable.</p>
<p>Habit stacking helps: attach the Focusing Question to an existing anchor such as coffee or sitting at the desk. Same place, same time, same first action. Identity shifts from “I try to focus” to “I am someone who protects the first block.” Identity language makes misses feel like incongruence worth correcting.</p>
<p>Celebrate block completion briefly, not only big outcomes. Outcome rewards arrive late; process rewards keep the streak alive through flat weeks when dominoes feel heavy and invisible.</p>
<p><strong>Lesson:</strong> Turn the Focusing Question and time block into a daily habit — successive focused days compound into extraordinary outcomes.</p>
<h3>Chapter 11: Applying The One Thing across life domains</h3>
<p>Although many readers meet the book through work, Keller applies the logic across life. Health has a ONE Thing for a season — perhaps sleep, walking, or cooking at home — that makes other health goals easier. Relationships have a ONE Thing — a weekly undistracted evening, a hard conversation, a shared project. Spiritual or personal growth practices can be focused the same way rather than collecting unread books and abandoned apps.</p>
<p>The danger of multiple domains is returning to scattered effort under a new label: one thing for work, one for health, one for marriage, one for hobbies, all daily, which recreates overload. Keller’s nesting and counterbalancing help. Pick the domain that is currently the lead constraint on your life’s purpose, go deep there, and maintain other domains at a healthy minimum until the season shifts.</p>
<p>Families and teams can use a shared Focusing Question. What is the ONE Thing we can do this quarter such that everything else becomes easier? Shared focus reduces conflict born from unspoken competing priorities. It also makes saying no collectively easier.</p>
<p>At work, managers can ask the question for the team’s outcomes and protect maker time as fiercely as meeting time. Cultures that celebrate responsiveness above all else systematically destroy ONE Thing progress, then wonder why strategy never ships.</p>
<p>Choose one personal domain besides work and name its ONE Thing for the next thirty days. Keep career focus, but stop pretending eight priorities across life can all be “first.”</p>
<p>Beware the productivity trap of optimizing leisure into another performance metric. Rest can be a supporting ONE Thing in a recovery season without becoming a hustle. The question still helps: What is the ONE Thing I can do for recovery such that everything else becomes easier? Sometimes the answer is sleep, not another self-improvement podcast.</p>
<p>In parenting or partnership, a shared weekly Focusing Question meeting — twenty minutes — can prevent a house full of competing unspoken priorities. Align the lead domino; then stop renegotiating it daily.</p>
<p><strong>Lesson:</strong> Apply the ONE Thing across life with nesting and seasons — do not multiply “one things” into a new form of overload.</p>
<h3>Chapter 12: From focus philosophy to lived results</h3>
<p>The One Thing’s lasting value is not a slogan; it is a operating system for attention. Go small in focus. Ask the Focusing Question. Line up dominoes. Time-block the lead action early. Reject multitasking myths and equal-urgency lies. Connect purpose to priority to productivity. Defend the block from thieves. Accept tradeoffs. Repeat until successive success becomes your normal.</p>
<p>Readers who only underline quotes will not change. Readers who change their calendar will. The book is blunt because the problem is blunt: you cannot exceed the results your focus deserves. Talent, credentials, and tools matter less than whether your best hours regularly touch your most important outcome.</p>
<p>Begin tomorrow morning. Before inbox, answer the Focusing Question in writing. Block two hours if you can, one if you must. Close the portals of interruption. Do the lead domino. Then let the rest of the day be as reactive as it needs to be. Repeat. In ninety days, compare your position to a ninety-day stretch of scattered effort. The difference is the book’s argument made visible.</p>
<p>Extraordinary results are available to ordinary people who become unusual in their willingness to choose. Keller’s invitation is not to do everything better. It is to do the right thing first, long enough for the chain of dominoes to reach something that once looked out of reach.</p>
<p>Teach the method by modeling it. Children and colleagues learn what you protect, not what you preach. If you say focus matters and answer every ping instantly, you taught pings. If you say relationships matter and never block time for them, you taught neglect.</p>
<p>Finally, reread the Focusing Question when life changes — new role, new baby, new health constraint. The ONE Thing is allowed to change. What must not change is the discipline of having one, protecting it, and letting successive days do what scattered ambition cannot.</p>
<p><strong>Lesson:</strong> Live the method daily — Focusing Question, protected block, successive dominoes — until focus compounds into extraordinary results.</p>',
  duration_minutes = 25,
  cover_image_url = 'https://covers.openlibrary.org/b/isbn/9781885167774-L.jpg',
  short_description = 'Gary Keller’s focus classic: the Focusing Question, successive dominoes, time blocking, and going small to achieve big results.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'The One Thing';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'The One Thing');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('What is Keller’s Focusing Question aimed at finding?', 'Every task on a long list', 'The one action that makes everything else easier or unnecessary', 'Only recreational hobbies', 'What others want you to do first', 'B', 1),
  ('What does ''go small'' mean in The One Thing?', 'Think tiny goals forever', 'Narrow focus to the highest-leverage priority to achieve big results', 'Avoid ambition', 'Do only easy tasks', 'B', 2),
  ('Why does Keller emphasize time blocking?', 'Schedules don’t matter', 'To protect a non-negotiable period for the ONE Thing before interruptions win', 'To fill the day with meetings', 'To multitask better', 'B', 3),
  ('What is the domino metaphor about?', 'Playing games at work', 'Lining up priorities so successive successes unlock larger outcomes', 'Knocking over competitors personally', 'Avoiding planning', 'B', 4),
  ('When should you typically do your ONE Thing, per Keller’s willpower view?', 'When completely exhausted', 'When willpower and energy are freshest — often early', 'Only on weekends', 'After all emails are zero', 'B', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'The One Thing';
