UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Peace is found in the present</h2>
<ul><li>The Now is primary; most suffering intensifies when attention is lost in mental stories about past and future.</li></ul>
<h2>2. You are not your thinking</h2>
<ul><li>Disidentify from the stream of thought; consciousness can watch the mind without being trapped as the mind.</li></ul>
<h2>3. Psychological time fuels unease</h2>
<ul><li>Clock time is useful for planning; psychological time is compulsive living inside memory and anticipation.</li></ul>
<h2>4. The ego needs identification and conflict</h2>
<ul><li>Egoic identity thrives on roles, complaints, and mental positions that keep “me” separate and incomplete.</li></ul>
<h2>5. The pain-body feeds on negativity</h2>
<ul><li>Accumulated emotional pain can activate, seek drama, and recycle old hurt until presence interrupts it.</li></ul>
<h2>6. Presence withdraws fuel from suffering</h2>
<ul><li>Observing thoughts and emotions without becoming them reduces identification and softens reactivity.</li></ul>
<h2>7. Simple anchors restore the Now</h2>
<ul><li>Breath, inner-body sensing, and attention to immediate perception are practical portals into presence.</li></ul>
<h2>8. Acceptance transforms the quality of action</h2>
<ul><li>Aligning with what is — then acting — ends the friction of resisting the present moment.</li></ul>

<h1>PART 2 — THE POWER OF NOW</h1>
<h2>A 26-Minute Read Summary</h2>

<h3>Chapter 1: The Primacy of the Present Moment</h3>
<p>Eckhart Tolle’s teaching begins with a radical simplicity: life is only ever happening now. The past exists as memory arising in the present; the future exists as anticipation arising in the present. Yet most people live as if the Now were a thin bridge between more important mental destinations. They rush through this moment to get to a better one, or they drag previous moments into this one as unfinished stories. The result is a background of unease — waiting, regretting, rehearsing, comparing — that rarely pauses long enough to notice that peace was available in the only place it can be felt: here.</p>
<p>This is not an argument against goals or calendars. Tolle distinguishes practical planning from psychological captivity. You can schedule tomorrow while remaining rooted in today’s alertness. Problems arise when identity migrates into the timeline — when “I” becomes the person who will finally be okay after the next achievement, apology, or escape. Presence reverses that migration. Attention returns to what is actually occurring: breath, body, sounds, the simple fact of being. From that rootedness, action becomes cleaner because it is not constantly fighting the moment it must use.</p>
<p>Readers often meet the book in exhaustion — after years of thinking their way toward relief and finding that thinking multiplied the noise. Tolle’s invitation is experiential rather than merely intellectual. Understanding the idea of presence helps; tasting presence changes the nervous system’s default. The chapters that follow map how mind-identification creates suffering, how the ego and pain-body keep the loop alive, and how ordinary anchors can reopen the gate to the Now without requiring a monastery.</p>
<p>A simple experiment reveals how rarely the Now is inhabited. Set a timer for three minutes and intend to stay with raw sensory experience — breath, contact points, ambient sound — without running a commentary. Most people discover the mind leaves within seconds, planning dinner or replaying a slight. That discovery is not failure; it is diagnosis. The habitual departure is the suffering engine Tolle describes. Each gentle return is the medicine. You do not need dramatic mystical experiences. You need frequency: many small returns that teach attention it has a home other than story.</p>
<p><strong>Lesson:</strong> Treat the present moment as primary reality; past and future are mental contents appearing now.</p>

<h3>Chapter 2: You Are Not Your Mind</h3>
<p>A core move in The Power of Now is disidentification from thought. The mind produces a nearly continuous commentary — judgments, worries, fantasies, self-talk. Most people fuse with that commentary and call it “me.” Tolle points to a deeper fact of experience: there is awareness in which thoughts appear and disappear. When you notice a thought as a thought, a gap opens. In that gap, you are not trapped inside the narrative. You are the space that knows the narrative is happening.</p>
<p>This does not mean thinking is evil or useless. Thinking is a tool. The problem is compulsive, unconscious thinking that claims ownership of identity. When every emotion immediately becomes a story (“This always happens to me,” “They disrespect me,” “I’ll never be safe”), suffering thickens. Presence softens the glue between awareness and content. You can feel fear without becoming a fearful self-concept. You can have a planning thought without drowning in future dread. The shift is subtle and profound: from being the thinker to knowing the thinking.</p>
<p>Practice starts small. For one minute, watch thoughts the way you might watch clouds. Do not fight them; fighting is more mind. Simply notice arising and passing. When you realize you were lost in a story, that realization is already presence. Celebrate the noticing rather than punishing the wandering. Over time, the density of identification lessens. Life does not become thought-free; it becomes less possessed by thought. That is the beginning of freedom Tolle describes — not a blank mind, but an awake relationship to the mind.</p>
<p>Language helps create the gap. Prefer “a worried thought is here” over “I am a wreck.” Prefer “anger is moving through” over “I am my anger.” This is not denial; it is accurate phenomenology. Thoughts and emotions are events in consciousness. When grammar fuses you with them, choice narrows. When grammar allows space, response options reappear — breathe, delay, speak cleanly, leave the room. Over weeks, this linguistic shift becomes an embodied reflex. You still think; you are less imprisoned by thinking. That is the practical meaning of “you are not your mind.”</p>
<p><strong>Lesson:</strong> Practice watching thoughts as events in awareness so you stop mistaking mental commentary for your identity.</p>

<h3>Chapter 3: Psychological Time Versus Clock Time</h3>
<p>Tolle draws a crucial distinction between clock time and psychological time. Clock time is the practical use of past learning and future planning — arriving at appointments, cooking a meal, building a career step by step. Psychological time is living primarily inside mental movies of what was and what might be, using the present only as a means. In psychological time, the Now is never enough; it is always a corridor. Anxiety often lives in anticipated futures. Guilt and resentment often live in recycled pasts. Both pull attention out of the only moment where life can be touched.</p>
<p>Many people believe they are “facing reality” when they are actually rehearsing catastrophe or replaying injury. The body responds as if the story were happening, flooding stress chemistry into a moment that may otherwise be workable. Presence does not deny that difficult events occurred or that preparation matters. It refuses to let unfinished mental time colonize every second. You remember in order to learn; you plan in order to act; then you return. The return is the discipline.</p>
<p>A useful check is: Is this thought serving a practical next step, or is it looping without arrival? If looping, bring attention to sense perception — feet on floor, air at nostrils, ambient sound. Let the thought continue if it must, but do not feed it with total identity. Clock time stays available; psychological time loses its trance. That single discrimination — useful thought versus compulsive time-travel — can reduce a surprising amount of daily suffering without solving every external problem.</p>
<p>Notice how devices intensify psychological time. Endless feeds pull you into other people’s pasts and futures while your body sits unused in a chair. Notifications yank attention into anticipatory tension. A presence practice for modern life is deliberate single-tasking with phone out of reach for short blocks. During the block, whenever the urge to time-travel arises, feel the urge as sensation and return to the task’s textures. You are training the muscle that Tolle’s entire book relies on: the ability to be where your body already is.</p>
<p><strong>Lesson:</strong> Use clock time for practical planning; refuse psychological time’s habit of living inside past and future stories.</p>

<h3>Chapter 4: Ego, Roles, and the Need to Be Right</h3>
<p>For Tolle, ego is not merely arrogance. It is a sense of self built from mental identification — with roles, possessions, history, opinions, victimhood, or superiority. Because this self is made of forms, it feels incomplete and unstable. It seeks more forms to reinforce itself: more status, more agreement, more drama, more proof. Conflict becomes strangely attractive because opposition defines the “me.” Being right can matter more than being at peace, because rightness feeds identity.</p>
<p>Watch how quickly a conversation becomes a battlefield of positions. The content may be trivial; the egoic charge is not. Someone threatens an image you hold, and the body tightens, the voice sharpens, the mind gathers evidence. Presence asks a different question: Can I notice the energy of needing to win without obeying it? Can I speak truthfully without using truth as a weapon for selfhood? Humility here is not self-erasure; it is freedom from compulsive self-construction.</p>
<p>Roles are useful until they swallow you. Parent, professional, partner, expert — each can be lived consciously or unconsciously. Unconscious role-identity creates fear of loss: if the role wobbles, “I” seem to die. Conscious living holds roles lightly as functions within the larger field of presence. You still act responsibly; you stop demanding that the role complete you. That shift reduces the background panic that drives overwork, people-pleasing, domination, and endless comparison.</p>
<p>Try a conversational fast: for one discussion a day, enter with the aim to understand rather than to win. Ask one more question than you want to. Notice the ego’s itch when your image is unconfirmed. That itch is information. You do not have to indulge it. Similarly, practice doing a small helpful act without advertising it. Ego often wants witnesses; presence can enjoy the act itself. These micro-disciplines shrink the ego’s demand for constant reinforcement and make ordinary days less combative.</p>
<p><strong>Lesson:</strong> Notice when identity clings to roles and being right; let presence hold the role so ego stops running the conflict.</p>

<h3>Chapter 5: The Pain-Body and Emotional Recycling</h3>
<p>Tolle describes the pain-body as accumulated emotional pain that can lie dormant and then activate. When active, it seeks experiences that resonate with its frequency — conflict, grievance, catastrophic thinking, addictive soothing that eventually deepens hurt. People often say “I don’t know what came over me” after an outburst; something old was feeding. The pain-body is not a medical diagnosis in Tolle’s usage; it is a phenomenological map of how unprocessed pain becomes a semi-autonomous pattern.</p>
<p>Activation often begins with a trigger: a tone of voice, a familiar slight, a lonely evening, a stress spike. Thought and emotion then lock together, creating a story that justifies more pain. The loop is self-reinforcing. Presence interrupts the loop by making the pain conscious without becoming it. You feel the heaviness, heat, or ache in the body. You name activation gently: pain is here. You refrain from the usual narrative fuel — blaming texts, revenge fantasies, identity conclusions. Feeling fully while watching is the opposite of suppression and the opposite of drama.</p>
<p>Over repeated interruptions, the pain-body loses density because it is no longer fed. This does not mean never grieving or never setting boundaries. It means refusing to let old pain drive unconscious harm to yourself and others. Relationships improve when both people can recognize activation and pause. Individually, you reclaim choice: to breathe, to delay reply, to move the body, to stay present with sensation until the wave peaks and falls without a new story bolted on top.</p>
<p>Know your personal activation windows — fatigue, hunger, loneliness, certain relatives, certain hours of night. Prevention is presence too: sleep, food, and fewer needless triggers are not unspiritual; they reduce unnecessary pain-body fuel. When activation is already strong, prioritize delay. Do not send the message, make the vow, or quit the job in the spike. Wait until presence returns enough to distinguish old pain from present facts. That single habit prevents enormous relational damage and teaches the pain-body it will not be obeyed automatically.</p>
<p><strong>Lesson:</strong> When old pain activates, feel it in the body and withhold the story-fuel that keeps the pain-body alive.</p>

<h3>Chapter 6: Presence as the End of Identification</h3>
<p>Presence, for Tolle, is alert stillness — awareness resting in itself while engaging the world. It is not zoning out. It is more here, not less. When presence rises, identification with thought and emotion weakens. Pain may still be felt, but it is no longer who you are. That distinction is the hinge of freedom. Suffering, in this teaching, is largely resistance plus story. Sensation becomes suffering when the mind declares it unacceptable and builds an identity around it.</p>
<p>People sometimes fear that presence will make them passive. Tolle’s answer is that unconscious reactivity is not true power. Action from presence can be firm, clear, and intelligent because it is not distorted by compulsive fear or egoic escalation. You can leave a harmful situation, speak a boundary, or solve a problem more cleanly when you are not drowning in psychological time. Presence includes the courage to face what is — including the need to act.</p>
<p>A daily test helps: In this moment, am I arguing with reality, or am I meeting it? Argument with reality is the mind’s war against the Now. Meeting reality begins with acknowledgment: this is what is here. From acknowledgment, response can arise. Without acknowledgment, response is mostly reaction. The more often you practice meeting, the more life feels inhabited rather than postponed. That inhabited quality is what many readers recognize as the peace they were chasing elsewhere.</p>
<p>Presence includes allowing pleasure without clinging and allowing pain without collapse. Clinging turns joy into fear of loss; collapse turns pain into identity. The middle is intimate contact with what is, plus willingness to let it change. This is why Tolle links presence to peace that does not depend on perfect circumstances. Circumstances rotate. Presence can be tasted in a traffic jam and forgotten in a palace. The work is choosing presence as the relationship to circumstance, not waiting for circumstance to deserve your attention.</p>
<p><strong>Lesson:</strong> Presence means meeting this moment alertly so you stop being identical with pain, thought, and resistance.</p>

<h3>Chapter 7: Portals Into the Now</h3>
<p>Tolle offers practical portals — simple attention practices that reopen presence. The breath is one. Feeling one or two conscious breaths interrupts mental momentum. Sense perception is another: truly hearing a sound, seeing light on a wall, touching the texture of an object without labeling it to death. These are not tricks to add to a crowded self-improvement list; they are ways of reclaiming the aliveness already here.</p>
<p>Inner-body awareness is especially emphasized. Place attention inside the hands, the chest, the field of subtle aliveness in the body. Thinking tends to thin when attention densifies in bodily presence. You can practice this in line at a store, in a difficult meeting, or while walking. The world continues; your center of gravity shifts from head-spin to embodied here-ness. For many people, this is the most reliable on-ramp when anxiety accelerates.</p>
<p>Silence and stillness are portals too — not necessarily external silence, but the inner recognition of stillness underneath noise. Even one conscious pause before speaking can change a relationship. The point is frequency, not duration. Ten seconds of real presence, repeated often, rewires the habit of absence more effectively than rare hour-long sessions used as spiritual performance. Use ordinary life as the monastery: dishes, commuting, listening. Each is a chance to return.</p>
<p>Stack portals onto existing habits. Feel two breaths before unlocking your phone. Feel your hands on the wheel before driving. Feel your feet when an argument starts. Habit stacking removes the need to remember a separate spiritual schedule. If you enjoy formal sitting meditation, keep it — and refuse to treat it as the only sacred zone. Tolle’s portals are democratic: available to busy people, skeptical people, and anyone willing to notice one sensation fully. Depth grows from sincerity of attention, not from exotic technique.</p>
<p><strong>Lesson:</strong> Use breath, sensing, and inner-body attention as everyday portals that return you to the Now.</p>

<h3>Chapter 8: Acceptance, Surrender, and Effective Action</h3>
<p>Surrender in Tolle’s sense is not defeat. It is the end of inner resistance to what already is. The present moment may contain discomfort, loss, or unfairness. Resistance multiplies the pain with a second layer: This should not be happening to me. Acceptance removes that second layer so intelligence can operate. You accept that the tire is flat; then you change it. You accept that a conversation is hard; then you speak honestly. Non-acceptance often looks like action but is mostly friction.</p>
<p>People confuse acceptance with approval. You can accept the fact of a situation and still work to change it. What you drop is the exhausting war against the Now as a personal insult. That war keeps the ego supplied with grievance. Surrender returns energy to response. Paradoxically, people who practice this often become more effective, not less, because clarity replaces fog. They also become kinder, because they are less busy defending a wounded story of how reality failed them.</p>
<p>Try a simple sequence when stressed: pause, feel the body, acknowledge “this is what is here,” ask “what is the next clean action?” If no action is available, stay with presence itself. Waiting without psychological time is very different from waiting while rehearsing misery. One is stillness with open eyes; the other is future-obsession wearing a present-tense mask. Surrender is choosing the first, again and again, until it becomes a new default.</p>
<p>In crises, surrender can sound impossible. Start with tiny acceptances: accept that you feel afraid; accept that the email arrived; accept that the body is tired. These acceptances do not solve the crisis; they stop the useless second fight. From there, list controllable next actions in clock time — call, rest, document, ask for help — and do one. Presence makes the list cleaner because fear is felt rather than obeyed as destiny. Surrender is thus deeply practical: it returns bandwidth to response.</p>
<p><strong>Lesson:</strong> Surrender means ending resistance to what is so you can act clearly — not approving harm or becoming passive.</p>

<h3>Chapter 9: Relationships as Spiritual Practice</h3>
<p>Close relationships trigger the mind and pain-body with unmatched speed. That makes them powerful places for presence. Tolle suggests bringing alertness into listening — hearing without immediately preparing a defense. When activation rises, name it inwardly and slow down. Many fights are two pain-bodies seeking food. If even one person stays present, the pattern often loses fuel. If both collapse into identification, the familiar tragedy replays.</p>
<p>Love, in this framing, is not the ego’s attachment or neediness. It is the recognition of shared being beneath forms and stories. From that recognition, care becomes less possessive. You can appreciate a partner without demanding they complete your incomplete self-image. You can leave a destructive dynamic without hatred as the engine. Presence does not guarantee a relationship continues; it guarantees you stop using the relationship unconsciously as a drama generator for identity.</p>
<p>Practical intimacy skills align with the teaching: pause before reactive texts, feel your feet during criticism, ask what is true now rather than what ancient script is firing. Celebrate moments of real meeting — eye contact, quiet companionship, honest repair. These moments train the nervous system to prefer presence over performance. A relationship becomes spiritual not by being perfect, but by being a repeated invitation to wake up together.</p>
<p>Alone time also trains relational presence. If you cannot sit with yourself without distraction, other people become tools for escape. Practice short periods of undistracted solitude — no input, just breath and body — so you bring a less hungry ego into connection. Then, in conversation, offer the gift you want to receive: attention. Presence is contagious in the best sense. One rooted person can calm a room without lecturing anyone about spirituality. Being the rooted person is the practice.</p>
<p><strong>Lesson:</strong> Use relationship triggers as cues to stay present, listen deeply, and refuse to feed mutual pain-body drama.</p>

<h3>Chapter 10: The Inner Body as Anchor</h3>
<p>Returning to the inner body deserves its own emphasis because it is so practical under pressure. When the mind races, abstract instructions to “be present” can fail. Feeling the aliveness in your hands or the rise of the belly gives attention a concrete home. This is not analysis of the body; it is inhabiting it. As attention stabilizes there, thoughts may continue at the edges, but they lose hypnotic power. You become rooted in Now through sensation.</p>
<p>You can expand the practice: feel the whole body as a single field while walking or sitting. Combine with breath. If strong emotion arises, locate it as sensation — tightness, heat, hollowness — and keep a portion of attention in the larger inner-body field so you are not swallowed by one knot. This is how presence holds pain without suppression. The emotion is welcomed into awareness; the story is not automatically believed.</p>
<p>Used throughout the day, inner-body awareness becomes a mobile refuge. Before a hard call, drop into the chest and hands for ten seconds. In insomnia, feel the body instead of wrestling thoughts. In joy, inhabit the moment fully so happiness is not immediately turned into fear of loss. The body is always now; the mind rarely is. Choosing the body as anchor is choosing reality’s doorway.</p>
<p>If trauma history makes body attention intense, go gently and consider professional support. Presence is not a substitute for therapy; it can complement healing by reducing secondary story-suffering. Begin with neutral areas like hands or feet rather than forcing attention into the most charged regions. The aim is befriending embodiment, not flooding yourself. Over time, many people find the inner body becomes a trustworthy ally — a place to return when the mind’s forecasts become unbearable.</p>
<p><strong>Lesson:</strong> Anchor attention in inner-body sensation to stabilize presence when the mind wants to time-travel.</p>

<h3>Chapter 11: Consciousness, Stillness, and Ordinary Life</h3>
<p>Tolle points beyond personal improvement toward consciousness itself — the aware stillness in which experience appears. You do not need complex metaphysics to practice this. You need willingness to notice the quiet underneath noise. In that quiet, the compulsive search for the next thing softens. Ordinary activities become luminous not because they change, but because you are finally there for them. Washing a cup can be as complete as a retreat if presence is total.</p>
<p>This perspective reorders priorities. Success and failure still occur, but they no longer define the whole of identity. The present moment becomes friendlier even when circumstances are hard, because you stop abandoning yourself into mental escape. Creativity often improves: insight needs space, and presence creates space. Compassion grows because you recognize the same unconscious pain patterns in others without needing to merge with their drama.</p>
<p>Live the teaching in modest doses. One conscious breath at a doorway. One fully felt sip of water. One conversation where you listen to the end. These are not small; they are the actual transformation. Spiritual life, in Tolle’s sense, is not elsewhere. It is the depth of this. When you forget — and you will — the forgetting becomes the next bell. Return without drama. The power of Now is not a single awakening story; it is the repeated miracle of coming back.</p>
<p>Beware spiritual ego — using presence language to feel superior, avoid responsibilities, or bypass messy feelings. Tolle’s stillness includes ethical clarity and ordinary human care. If “I’m being present” becomes an excuse to ignore consequences, you have built another identity form. Keep checking: Is this presence making me more honest, kind, and effective — or more defended? Real stillness softens the need to perform spiritually. It returns you to simple humanity: wash the dish, tell the truth, feel the breath, begin again.</p>
<p><strong>Lesson:</strong> Bring stillness into ordinary actions; presence in small moments is the real spiritual practice.</p>

<h3>Chapter 12: Living From the Now</h3>
<p>Integrating The Power of Now means letting presence become the default orientation rather than an emergency tool. Start mornings with a short check-in: Can I feel the body? Can I notice breath? Throughout work, use transitions as bells. At night, release the day without endlessly reprocessing it in psychological time. When pain-body weather arrives, treat it as weather — real, temporary, observable — not as identity. When ego wants a war, ask whether peace is available if you drop the need to be right.</p>
<p>Keep the teaching humane. Presence is not emotional numbness. Grief can be present. Joy can be present. Anger can be felt and then guided into clean action. What drops away is the unconscious fusion that turns every feeling into a destiny story. You become someone who can inhabit intensity without becoming unconscious. That capacity changes careers, health habits, and love because choice returns to the moment where choice actually exists.</p>
<p>Carry one sentence as a companion: What is my relationship to this moment? If the relationship is resistance, soften. If it is absence, return. If it is presence, continue. Tolle’s book is ultimately not about collecting ideas; it is about tasting the alive stillness that ideas point toward. Return there often enough, and life stops being a problem to solve later and becomes a reality to meet now — which was always the only place it could be met.</p>
<p>End with a portable question for hard moments: Can I meet this without fleeing into story? If yes, stay. If not yet, use a portal until yes becomes possible. Read Tolle as a companion for practice, not as a belief system to argue about. The power named in the title is not power over others; it is power to inhabit your own life. That power grows quietly each time you return. Let returning be enough. The Now does not need your perfection — only your attention.</p>
<p><strong>Lesson:</strong> Make presence a daily orientation: return often, meet what is here, and let action arise from the Now rather than from mental escape.</p>
<h3>Chapter 13: Presence Under Pressure</h3>
<p>The deepest test of Tolle’s teaching is not a quiet morning; it is conflict, grief, deadline panic, or illness. Under pressure, psychological time screams. Ego grabs for control. Pain-body looks for a host. This is when portals matter most. One breath. Feet on the floor. Hands alive. A two-second acceptance: this is what is here. Then the next clean action. You will forget. Forgetting is normal. The path is measured by returns per day, not by uninterrupted bliss.</p>
<p>Build a pressure protocol in advance so you need not invent spirituality mid-spike. Example: pause speaking, feel the inner body for twenty seconds, ask whether the urge is practical or compulsive, then choose. Share the protocol with a partner if helpful: “If I go sharp, I may take a short presence break before we continue.” This is adult intimacy, not avoidance. Presence under pressure also means feeling sorrow fully when loss is real, without the extra story that reality has personally betrayed your destiny.</p>
<p>In the end, The Power of Now is a training manual for inhabiting your life. Read it, practice it, forget it, return to it. Let ordinary days be the curriculum. Peace is not elsewhere. Peace is the quality of attention you bring to here. Keep bringing it. That is the whole teaching in motion.</p>
<p><strong>Lesson:</strong> Prepare simple presence protocols for high-pressure moments, and measure progress by how often you return to the Now.</p>
',
  duration_minutes = 26,
  cover_image_url = 'https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg',
  short_description = 'Eckhart Tolle’s guide to presence — disidentifying from egoic thinking, psychological time, the pain-body, and returning to the Now.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'The Power of Now';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'The Power of Now');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('What does Tolle say is ultimately real and primary for peace?', 'Only the future', 'The present moment (the Now)', 'Only memories', 'Other people’s opinions', 'B', 1),
  ('What is psychological time in Tolle’s teaching?', 'A clock on the wall', 'Living absorbed in past/future mental stories rather than the present', 'Airport schedules', 'Meditation timers only', 'B', 2),
  ('What is the pain-body?', 'A gym injury only', 'Accumulated emotional pain that can activate and feed on negativity', 'A medical diagnosis for everyone', 'A type of meditation cushion', 'B', 3),
  ('How does presence affect identification with pain?', 'It always increases drama', 'Observing without becoming the pain withdraws identification', 'It requires arguing with every thought', 'It means suppressing all feeling forever', 'B', 4),
  ('Which practice fits Tolle’s approach?', 'Constant multitasking', 'Anchoring attention in breath / inner body / present sensing', 'Refreshing social feeds', 'Replaying regrets all day', 'B', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'The Power of Now';
