UPDATE public.information
SET
  content_text = '<h1>PART 1 — KEY LESSONS (OUTLINE)</h1>
<h2>1. Care selectively, not never</h2>
<ul><li>Not giving a f*ck means choosing what deserves your limited attention and energy, not becoming numb.</li></ul>
<h2>2. The backwards law</h2>
<ul><li>Chasing constant positivity often increases anxiety; accepting struggle reduces its power over you.</li></ul>
<h2>3. Break the Feedback Loop from Hell</h2>
<ul><li>Feeling bad about feeling bad multiplies suffering; drop the secondary self-judgment.</li></ul>
<h2>4. Values determine the quality of your problems</h2>
<ul><li>Good values are reality-based, socially constructive, and within your control.</li></ul>
<h2>5. Responsibility is not the same as fault</h2>
<ul><li>You may not cause every event, but you own your response and next choices.</li></ul>
<h2>6. Certainty is a trap</h2>
<ul><li>Growth requires admitting you might be wrong and updating your map of the world.</li></ul>
<h2>7. Failure and boundaries are tools</h2>
<ul><li>Progress comes through trying, failing, and saying no to what dilutes what matters.</li></ul>

<h1>PART 2 — THE SUBTLE ART OF NOT GIVING A F*CK</h1>
<h2>A 25-Minute Read Summary</h2>

<h3>Chapter 1: The Subtle Art of Caring Less About More</h3>
<p>Mark Manson’s central claim is not that you should care about nothing. It is that you already care about too many shallow things, and that habit is exhausting you. Modern culture sells the idea that you should feel extraordinary, happy, and optimized at all times. When ordinary life shows up instead — boredom, rejection, average performance, awkward conversations — people panic. They assume something is wrong with them for being human. The marketplace then offers endless fixes, implying that if you care hard enough about self-improvement theater, discomfort will finally leave you alone.</p>
<p>Manson flips that story. Your capacity to care is limited. Every time you obsess over a stranger’s opinion, a status comparison, a minor inconvenience, or a social-media slight, you spend a unit of care that could have gone to a meaningful relationship, a craft you respect, or a problem worth solving. “Not giving a f*ck” is therefore a budgeting skill. You stop overspending emotional energy on noise so you can afford to spend it on signal. Indifference to everything is not maturity; it is emptiness. Selective caring is maturity.</p>
<p>Practically, this means auditing your week with uncomfortable honesty. List what triggered irritation, envy, outrage, or rumination. Ask which of those reactions protected a real value — health, family, integrity, craft — and which only protected your ego’s need to look superior or unhurt. Notice how often you give intense care to things you would not defend in a serious conversation about your life’s purpose. The goal is not to become cold. The goal is discrimination: fewer cheap cares, more expensive ones that build a life you can stand behind when no one is clapping.</p>
<p>Start with a simple rule for the next seven days: before you escalate emotionally, ask, “Is this worth a f*ck?” If the honest answer is no, redirect attention to one chosen priority. Over time, that question becomes a filter that protects your best energy from being nickeled-and-dimed by trivia. People who seem calm are often not feeling less; they are allocating better.</p>
<p>Selective caring also changes how you consume media. If a feed consistently manufactures cheap outrage, it is taxing your care budget on purpose. Curate inputs the way you would curate expenses. Every saved unit of attention can be reinvested in a hard conversation, a skill, or a person who actually shares your life.</p>
<p>Keep a written care budget for the week: three things that deserve your best energy and a short list of triggers you will refuse to escalate. Review it every Sunday so selective caring becomes a habit rather than a mood.</p>
<p>Notice also that selective caring is trainable under social pressure. Friends, coworkers, and feeds will keep handing you cheap cares — dramas, status contests, performative outrage. You do not owe every invitation your full emotional wallet. A polite decline of attention is not cruelty; it is how adults keep a center. Practice one declined rabbit hole per day and note what that freed-up hour actually funded.</p>
<p><strong>Lesson:</strong> Treat attention as a scarce budget and spend it only on what aligns with your deeper values.</p>

<h3>Chapter 2: The Backwards Law</h3>
<p>Drawing on ideas associated with Alan Watts, Manson describes the backwards law: the more desperately you pursue a feeling, the more you reinforce the sense that you lack it. Chase happiness as a permanent state and you train yourself to treat every emotional dip as failure. Demand constant confidence and insecurity becomes louder, because now insecurity threatens your identity as a “confident person.” Try to force people to like you and neediness becomes visible. Cling to total control and anxiety multiplies, because life refuses to be fully controlled.</p>
<p>Acceptance works in the opposite direction. When you allow discomfort without dramatizing it, discomfort loses some of its threat. You can feel anxious and still send the email. You can feel rejected and still keep your dignity. You can feel uncertain and still take the next honest step. Paradoxically, people who can sit with negative emotion often create more of the positive outcomes they wanted in the first place, because they are freer to act. Action no longer requires a perfect internal weather report.</p>
<p>This is not a call to romanticize suffering or refuse joy. It is a call to stop making good feelings a prerequisite for living. Use feelings as information, not as permission slips. If your metric for a good day is “I felt great the whole time,” you will keep losing, because no honest life delivers uninterrupted bliss. If your metric is “I acted according to my values despite imperfect feelings,” you start winning on a sturdier scoreboard. That shift alone can lower the volume of self-war.</p>
<p>A practical exercise: pick one avoided action that matters. Do it while naming the discomfort out loud — “I am nervous and doing it anyway.” Do not wait for the nervousness to leave. Notice that the feeling and the action can coexist. That coexistence is the backwards law in practice, and it is one of the fastest ways to regain agency.</p>
<p>Parents, managers, and partners can misuse positivity by demanding cheerfulness instead of honesty. Manson’s framing supports a healthier climate: feelings are allowed; values still lead. You can validate emotion without letting emotion veto every hard but necessary action.</p>
<p>When you notice the Feedback Loop from Hell starting, name it out loud and take one valued action within five minutes. Speed matters; rumination expands to fill whatever time you give it.</p>
<p><strong>Lesson:</strong> Stop demanding permanent positivity; accept struggle so you can act without waiting to feel perfect.</p>

<h3>Chapter 3: The Feedback Loop from Hell</h3>
<p>One of Manson’s most useful practical concepts is the Feedback Loop from Hell. First you feel anxious, lonely, angry, or inadequate. Then you judge yourself for feeling that way: “Normal people wouldn’t feel this. What’s wrong with me?” That second layer of self-attack creates more anxiety, more loneliness, and more inadequacy. The original emotion becomes a story about your defective character. You are no longer sad; you are “a sad person who can’t handle life.” The story is heavier than the feeling.</p>
<p>Social media intensifies the loop. Everyone else’s highlight reel becomes evidence that your private struggles are unique and shameful. The more you compare, the more you feel behind; the more you feel behind, the more you scroll for relief or validation; the scroll deepens the comparison. Advertising joins in by implying that your current emotional state is a problem to be purchased away. The loop feeds itself until ordinary human emotion feels like a personal emergency.</p>
<p>Interrupting it begins with a blunt permission: negative emotions are normal, not a personal scandal. You can feel insecure without making insecurity your identity. You can feel jealous without concluding you are morally broken. Manson’s tone is deliberately irreverent because humor punctures the solemn self-drama that keeps the loop spinning. Name the secondary judgment out loud: “I’m mad that I’m mad.” Then drop the second sentence. Feel the first feeling, breathe, and move your feet toward a valued action.</p>
<p>Also watch for the loop in relationships. People often punish partners for their own unprocessed shame, or withdraw because they are ashamed of needing comfort. Breaking the loop privately makes you less likely to export it. A useful mantra: “This feeling is allowed. The self-attack is optional.” Repeat until the optional part becomes believable.</p>
<p>If the loop is chronic and severe, professional support can help; Manson’s point is philosophical and practical, not a substitute for clinical care. For everyday spirals, the skill is simple and hard: stop adding a second war on top of the first feeling.</p>
<p>If a value cannot survive a tired Tuesday, it is still a preference. Test your top values on low-energy days and keep only the ones that still guide behavior when inspiration is absent.</p>
<p><strong>Lesson:</strong> Suffering multiplies when you punish yourself for having feelings; accept the feeling and refuse the self-judgment pile-on.</p>

<h3>Chapter 4: Happiness Is a Problem</h3>
<p>Manson argues that happiness is not a destination where problems end. Happiness is a byproduct of solving problems you care about. Life always contains struggle. The question is not whether you will have problems, but which problems you are willing to have. People who chase a problem-free existence become fragile, because every friction feels like injustice. They are not seeking happiness so much as seeking exemption from being human.</p>
<p>This reframes motivation in a bracing way. Instead of asking only “What do I want?” ask “What pain am I willing to sustain?” Wanting a fit body while refusing training discomfort is fantasy. Wanting deep relationships while refusing awkward honesty is fantasy. Wanting creative success while refusing rejection, revision, and invisibility is fantasy. Desire without an accepted form of suffering is just a mood with a vision board.</p>
<p>Application is concrete. For each goal, write the recurring pains that come with it — early mornings, boring practice, difficult conversations, delayed gratification, public mediocrity on the way to competence. If you will not accept those pains, revise the goal without self-contempt. If you will, stop waiting for inspiration and start paying the price on purpose. Happiness then becomes less mystical: it appears when your daily struggles match your chosen values, and when progress on those struggles gives you earned satisfaction.</p>
<p>Also notice that avoiding pain creates different pain: stagnation, regret, shallow relationships, bodies and skills that never develop. There is no pain-free lane. There is only chosen pain versus accidental pain. Adults choose. That choice is one of the book’s most practical definitions of maturity.</p>
<p>Try a weekly review question: “Which problem did I voluntarily work on, and which problem did I create by avoidance?” Over time, you will prefer the first category because it builds a life, while the second only postpones a bill.</p>
<p>When choosing problems, prefer those that compound skill, character, or connection. Petty problems — proving a stranger wrong online, polishing an image, winning trivial status — consume suffering without building a life. Worthy problems leave residue: a stronger body, a repaired relationship, a craft improved, a promise kept. If your weekly pain produces no residue you respect, you are renting struggle instead of investing it.</p>
<p><strong>Lesson:</strong> Choose problems worth having; happiness follows meaningful struggle, not the absence of struggle.</p>

<h3>Chapter 5: You Are Not Special</h3>
<p>Manson challenges the cultural message that everyone is exceptional and destined for unique greatness. The belief sounds kind, but it can quietly make ordinary life feel like failure. When average days, average talent, and average outcomes feel unacceptable, people either inflate themselves with empty confidence or collapse into resentment. Both are forms of entitlement: the universe owes me a feeling of specialness.</p>
<p>Accepting that you are not uniquely entitled does not mean aiming low. It means releasing the demand that reality constantly validate your centrality. Most worthwhile achievement is built from unglamorous repetition among people who are not mythical geniuses. Entitlement — whether the “I deserve success without sacrifice” kind or the “my suffering means rules don’t apply to me” kind — blocks growth because it replaces responsibility with identity performance. You spend energy defending a story instead of improving a skill.</p>
<p>A healthier posture is humble ambition: you can pursue excellence without needing to be the main character of every room. Measure yourself against your own standards and effort, not against a fantasy of destiny. Paradoxically, people who drop the specialness script often become more capable, because they can tolerate being beginners. Beginners look ordinary. Beginners ask dumb questions. Beginners fail in public. That is the doorway.</p>
<p>Try this reframe when envy hits: “Their highlight does not make my life a mistake.” Then return to one ordinary action that improves your actual domain. Specialness is a feeling. Usefulness is a practice. Manson bets on the practice.</p>
<p>In teams and families, drop the need to be the exceptional one in every conversation. Make room for other people’s competence. Ironically, people who do not need to be special are often trusted with more responsibility, because they are safer to work with.</p>
<p><strong>Lesson:</strong> Drop entitlement to exceptional treatment so you can do ordinary hard work that actually improves your life.</p>

<h3>Chapter 6: The Value of Suffering and Choosing Better Values</h3>
<p>If suffering is inevitable, values determine what your suffering means. Manson distinguishes better values from worse ones. Better values tend to be reality-based, socially constructive, and immediate or controllable — honesty, curiosity, vulnerability, standing up for yourself, taking responsibility. Worse values tend to be superstitious, socially destructive, or not controllable — being always right, being liked by everyone, chasing constant pleasure, measuring worth by status or superiority.</p>
<p>Bad values create bad problems. If your highest value is looking successful, every modest season becomes existential threat. If your highest value is never being disliked, every boundary feels dangerous. If your highest value is comfort, every challenge feels like an attack. If your highest value is being right, every disagreement becomes a war you must win. Good values create better problems: honest conversations that risk temporary friction, skill gaps you can train, responsibilities you can meet imperfectly, questions you do not yet know how to answer.</p>
<p>Do a values audit. For one week, notice what your emotions orbit around. Whatever repeatedly hijacks you is functioning as a value, whether you admit it or not. Then ask three questions: Is this based in reality? Does pursuing it make me more constructive toward others? Is it largely within my control? If a value fails those tests, it is expensive in the worst way. Replace metric theater — likes, status, being impressive — with metrics you can act on today: telling the truth, practicing the craft, keeping a promise, asking a sincere question.</p>
<p>Values are not posters. They are the criteria you use when two desires conflict. Write your top three. Use them as a decision filter for a month. Watch how many fake emergencies disappear when measured against them. That disappearing act is evidence you upgraded the operating system underneath your moods.</p>
<p>When values conflict internally — honesty versus kindness, ambition versus rest — choose consciously rather than by impulse. Manson’s standard still helps: prefer the value you can act on without denying reality or harming people as a strategy.</p>
<p><strong>Lesson:</strong> Upgrade your values; the quality of your life tracks the quality of what you choose to care about.</p>

<h3>Chapter 7: You Are Always Choosing</h3>
<p>Manson insists that we are always choosing, even when we pretend we are not. Saying “I had no choice” often means “I didn’t like the alternatives.” That linguistic dodge feels comforting, but it trains helplessness. Responsibility is the skill of seeing options — including unpleasant ones — and owning the tradeoff you select. Even in constrained situations, the response remains partly yours: what you focus on, what you practice next, whom you ask for help, what meaning you assign.</p>
<p>He separates fault from responsibility with unusual clarity. Fault is about the past cause of an event. Responsibility is about the present response. You can be hit by unfairness you did not cause and still be responsible for what you do next: seeking help, setting a boundary, learning a skill, leaving a situation, grieving, rebuilding, advocating. Confusing the two creates a trap: people refuse responsibility because accepting it feels like admitting fault. They stay stuck to protect a courtroom verdict about the past.</p>
<p>In practice, replace “This ruined me” with “Given this, what am I choosing now?” That question does not deny pain or injustice. It returns agency. Even choosing to rest, ask for support, or postpone a decision can be responsible when done consciously rather than as avoidance theater. What damages people is the story that they are permanent passengers in their own lives. Passengers wait. Responsible people steer with the vehicle they have, even if someone else caused the crash.</p>
<p>A weekly practice: write three situations where you felt powerless, then list one response option you still control in each. The list will not fix everything. It will restart the muscle of ownership that entitlement and victimhood both atrophy.</p>
<p>In conflict, responsibility sounds like “Here is my part,” not “This is all my fault.” That precision keeps relationships repairable. Blame arguments about the past; responsibility negotiations improve the next hour.</p>
<p><strong>Lesson:</strong> You may not be at fault for what happened, but you are responsible for what you do with it.</p>

<h3>Chapter 8: Certainty Is the Enemy of Growth</h3>
<p>Manson argues that certainty feels safe and often makes us stupid. The more absolutely we believe our story about ourselves, others, or the world, the less we notice contradictory evidence. Identity hardens. “I’m just not a math person,” “People always leave,” “I know how this ends,” “My type of person can’t change” — these claims protect us from the vulnerability of learning. They also freeze us in place.</p>
<p>His alternative is radical open-mindedness without becoming spineless. Assume you are wrong about something important, then go looking for it. Treat beliefs as hypotheses. Ask better questions. Seek people who disagree without making disagreement a war. This is uncomfortable because uncertainty threatens ego, but it is also how adults update. Children can afford certainty about cartoons. Adults who stay certain about everything become brittle.</p>
<p>Apply this in conflict and self-improvement. In an argument, aim to understand the strongest version of the other side before defending yourself. In personal growth, run small experiments instead of defending old self-concepts. Try the class. Take the feedback. Test the new habit for thirty days before announcing who you “are.” Being wrong becomes useful data rather than humiliation. Over time, your identity becomes more flexible and your decisions more reality-aligned. Humility, in this frame, is not self-hatred. It is epistemological honesty: your map is incomplete, so keep revising it.</p>
<p>One prompt for hard conversations: “What am I missing?” Ask it sincerely. If you cannot ask it, you are protecting certainty more than seeking truth. That alone is diagnostic.</p>
<p>Certainty addiction also shows up in politics, fandoms, and workplaces. Manson’s advice scales: hold identity lightly enough to learn, and hold values firmly enough to act. That balance is difficult — and worth practicing.</p>
<p><strong>Lesson:</strong> Hold beliefs lightly enough to revise them; growth requires trading false certainty for learning.</p>

<h3>Chapter 9: Failure Is the Way Forward</h3>
<p>Manson reframes failure as the path, not the opposite of success. Improvement is iterative: attempt, err, adjust, repeat. People who need to feel competent before they begin stay beginners forever. The fear of looking foolish becomes a cage decorated to look like high standards. Meanwhile, people willing to be bad at something long enough eventually become less bad, then good, then excellent. The difference is not magic talent. It is contact hours with reality.</p>
<p>He also challenges the motivational myth that you need to feel ready. Action often generates motivation more reliably than motivation generates action. Do a small, imperfect version first. Write the rough paragraph. Have the awkward conversation. Go to the gym for twenty minutes. Apply before you feel impressive. Momentum comes after contact with reality, not before. Waiting to feel ready is often a sophisticated form of avoidance.</p>
<p>Build a failure practice. Define a domain where you will tolerate beginner status publicly for ninety days. Track attempts instead of only outcomes. After each miss, ask one learning question: What specifically broke? What will I change next time? Who knows more than I do? This converts failure from identity verdict into process feedback — which is the only kind of failure that compounds into skill. If your self-worth requires never failing, you will unconsciously choose tiny goals that never ask you to grow.</p>
<p>Remember: rejection is data, not destiny. A “no” can mean “not yet,” “not this version,” or “not this audience.” Learners collect nos without making them a personality. That emotional skill is inseparable from Manson’s larger project of caring about the right things.</p>
<p>Share failure stories with people you trust. Secrecy makes failure feel unique and shameful; sunlight turns it into curriculum. Teams that can discuss misses improve faster than teams that perform invulnerability.</p>
<p><strong>Lesson:</strong> Take imperfect action first; failure is information that makes the next attempt smarter.</p>

<h3>Chapter 10: The Importance of Saying No</h3>
<p>Freedom, in Manson’s framing, requires rejection. If you say yes to everything, your life is no longer yours. Boundaries are how you protect the few things you have chosen to care about. This includes saying no to people, opportunities, identities, and even old versions of yourself that no longer fit your values. Without rejection, “yes” becomes meaningless because it is not a choice.</p>
<p>Many people fear that boundaries will make them selfish or unlovable. Manson’s point is the reverse: without rejection, intimacy and commitment are shallow. Choosing a partner means not choosing others. Choosing a craft means not chasing every trend. Choosing honesty means not performing endless agreeableness. Choosing a calm nervous system means not attending every conflict you are invited into. Depth requires exclusion. A life with no nos is a life with no center.</p>
<p>Practice clean nos without over-explaining. “I can’t take that on.” “That doesn’t work for me.” “I’m not available for that dynamic.” Expect discomfort — yours and sometimes theirs. Discomfort is not proof you are wrong; it is often proof a boundary is real. People who benefited from your lack of boundaries may protest. That protest is information about the old arrangement, not a verdict on your worth. Over time, the people and projects that remain will better match what you actually value.</p>
<p>Also say no to identity roles that cost too much: the perpetual fixer, the always-available friend, the person who never needs help. Those roles can look generous while quietly emptying the care budget you need for what matters most.</p>
<p>Schedule nos in advance where possible. Decide your non-negotiables for the quarter — family dinner, training days, deep work mornings — and treat conflicting requests as defaults to decline. Boundaries that are only invented in the moment are easier to negotiate away.</p>
<p><strong>Lesson:</strong> Protect what matters by rejecting what doesn’t; commitment requires saying no.</p>

<h3>Chapter 11: Death Clarifies What to Care About</h3>
<p>Manson closes much of his argument with mortality. Remembering that you will die is not meant to be morbid theater. It is a clarifying tool. Death shrinks the importance of petty status games and amplifies the importance of relationships, integrity, and contribution. Many of the f*cks we give are attempts to deny fragility — to look invulnerable, permanently relevant, endlessly impressive, or immune to loss. Mortality punctures that performance.</p>
<p>Confronting limits can make you more alive in the present. If time is finite, then choosing becomes sacred. You stop postponing the apology, the project, the trip, the hard conversation, the day with your kids that you keep trading for inbox zero. You also stop needing life to be a highlight reel. Ordinary moments with people you love become enough, because they are what the time was for. The chase for constant exceptionalism looks sillier when measured against a finite clock.</p>
<p>A simple practice: ask, “If I had five years left, would this still deserve my outrage, envy, or obsession?” If not, reclaim that care and redirect it. Another practice: write what you want people closest to you to feel about your presence, then check whether today’s cares serve that. Legacy, in this sense, is less about monuments and more about the quality of your chosen struggles and the people affected by them.</p>
<p>Death awareness can also reduce fear of embarrassment. Many social anxieties shrink when measured against a finite life. The meeting, the post, the awkward attempt — most will not matter. The relationships and integrity might. Allocate accordingly.</p>
<p>Used poorly, mortality thoughts can become nihilism. Used well, they become an editor. Manson wants the editor: cut the nonsense, keep the meaning, act while you can.</p>
<p><strong>Lesson:</strong> Let mortality edit your priorities so you stop wasting care on what will not matter.</p>

<h3>Chapter 12: Building a Life of Chosen Struggles</h3>
<p>Taken together, Manson’s ideas form a practical philosophy of adulthood. Stop trying to feel amazing all the time. Choose values that can survive contact with reality. Own your responses. Stay teachable. Fail forward. Draw boundaries. Remember you will die. None of this requires becoming cynical, cruel, or permanently ironic. It requires becoming selective. The world will always offer infinite things to care about. Your job is to refuse most of them without refusing life itself.</p>
<p>Start with one domain this week. Pick a value you want to live — honesty, health, craft, family presence, financial responsibility. Define the pain you accept in service of it. Define one boundary that protects it. Define one action you will take before you feel ready. Then watch for the Feedback Loop from Hell and interrupt it early. At week’s end, review: Did I spend my cares where I claimed they belong? Where did ego steal the budget?</p>
<p>The subtle art is emotional maturity dressed in blunt language: life is hard, you are not owed ease, and meaning comes from caring deeply about a few worthy things while releasing the rest. That is not apathy. That is focus. And focus, sustained over years with honest values, is how an ordinary person builds an uncommon life without needing to pretend they are special from the start.</p>
<p>If you remember only one line, make it this: give a f*ck about what is worth it, and get better at noticing what is not. Then practice that noticing until it becomes your default filter. In a culture that monetizes your outrage and insecurity, selective caring is both a mental health skill and a form of freedom.</p>
<p>Revisit this summary when you catch yourself drowning in cheap cares. The book’s usefulness is cyclical: you will forget, overcare, spiral, and need the backwards law again. Returning to the practice is itself a value — responsibility over perfection.</p>
<p><strong>Lesson:</strong> Design your week around a few chosen struggles and let everything else earn a much lower priority.</p>
',
  duration_minutes = 25,
  cover_image_url = 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg',
  short_description = 'Mark Manson’s counterintuitive guide to values — the backwards law, Feedback Loop from Hell, choosing what to care about, and responsibility over fault.',
  points_reward = 1,
  is_active = true,
  category = 'Books'
WHERE title = 'The Subtle Art of Not Giving a F*ck';

DELETE FROM public.questions
WHERE information_id IN (SELECT id FROM public.information WHERE title = 'The Subtle Art of Not Giving a F*ck');

INSERT INTO public.questions (
  information_id, question_text, option_a, option_b, option_c, option_d, correct_answer, question_order
)
SELECT i.id, q.question_text, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.question_order
FROM public.information i
CROSS JOIN (
  VALUES
  ('What is the Feedback Loop from Hell?', 'A workout plan', 'Feeling bad, then judging yourself for feeling bad, which multiplies suffering', 'A savings method', 'A networking strategy', 'B', 1),
  ('What does Manson say about ''not giving a f*ck''?', 'Care about nothing forever', 'Selectively care about what truly matters; stop wasting care everywhere', 'Never feel emotions', 'Avoid all responsibility', 'B', 2),
  ('Which are closer to Manson’s ''good values''?', 'Always being right and endless pleasure-chasing', 'Honesty, curiosity, and responsibility', 'Never being wrong', 'Constant performed positivity only', 'B', 3),
  ('What is the fault vs responsibility distinction?', 'They are identical', 'You may not be at fault for an event, but you are responsible for your response', 'Responsibility means blaming yourself for everything', 'Fault means you must fix others', 'B', 4),
  ('What is the backwards law idea in the book?', 'Wanting only positivity can create more negativity; accepting struggle can help', 'Always avoid hard things', 'Success needs zero discomfort', 'Feelings should be ignored permanently', 'A', 5)
) AS q(question_text, option_a, option_b, option_c, option_d, correct_answer, question_order)
WHERE i.title = 'The Subtle Art of Not Giving a F*ck';
